import dkd_test from 'node:test';
import dkd_assert from 'node:assert/strict';
import { dkd_friendlyReason } from '../src/dkd-friendly-reason';
import type { dkd_MatchContext } from '../src/dkd-football-context';
import type { dkd_Match } from '../src/dkd-types';

const dkd_match:dkd_Match={dkd_id:'dbo_test_plain_reason',dkd_league:'Test Lig',dkd_country:'TR',dkd_color:'#B6F36A',dkd_home:{dkd_id:'home',dkd_name:'Evspor',dkd_short:'EV',dkd_color:'#B6F36A',dkd_attack:1,dkd_defense:1,dkd_form:[]},dkd_away:{dkd_id:'away',dkd_name:'Deplasman SK',dkd_short:'DEP',dkd_color:'#6DBFFF',dkd_attack:1,dkd_defense:1,dkd_form:[]},dkd_offset:0,dkd_time:'20:00',dkd_startAt:'2026-09-23T17:00:00.000Z',dkd_sourceCount:2,dkd_quality:.8,dkd_explanation:'',dkd_lastSeenAt:'2026-09-22T16:00:00.000Z',dkd_venue:'',dkd_temperature:0,dkd_weather:'',dkd_xgHome:0,dkd_xgAway:0,dkd_markets:[{dkd_key:'home',dkd_label:'Maç sonucu 1',dkd_short:'MS 1',dkd_odds:1.85,dkd_probability:.52,dkd_group:'Maç sonucu'},{dkd_key:'draw',dkd_label:'Maç sonucu X',dkd_short:'MS X',dkd_odds:3.25,dkd_probability:.28,dkd_group:'Maç sonucu'},{dkd_key:'away',dkd_label:'Maç sonucu 2',dkd_short:'MS 2',dkd_odds:4.1,dkd_probability:.20,dkd_group:'Maç sonucu'}],dkd_history:[],dkd_absences:[1,0],dkd_rest:[5,3]};
const dkd_context:dkd_MatchContext={dkd_loaded:true,dkd_home:{dkd_teamName:'Evspor',dkd_sourceUrl:'https://example.test/home',dkd_logoUrl:null,dkd_loaded:true,dkd_standing:{dkd_position:3,dkd_played:10,dkd_wins:6,dkd_draws:2,dkd_losses:2,dkd_goals:'18:9',dkd_points:20},dkd_recent:[{dkd_date:'20.09.2026',dkd_opponent:'Deplasman SK',dkd_score:'2:1',dkd_venue:'home',dkd_result:'W'},{dkd_date:'15.09.2026',dkd_opponent:'Rakip A',dkd_score:'1:0',dkd_venue:'away',dkd_result:'L'},{dkd_date:'10.09.2026',dkd_opponent:'Rakip B',dkd_score:'3:0',dkd_venue:'home',dkd_result:'W'}]},dkd_away:{dkd_teamName:'Deplasman SK',dkd_sourceUrl:'https://example.test/away',dkd_logoUrl:null,dkd_loaded:true,dkd_standing:{dkd_position:9,dkd_played:10,dkd_wins:3,dkd_draws:2,dkd_losses:5,dkd_goals:'11:15',dkd_points:11},dkd_recent:[{dkd_date:'20.09.2026',dkd_opponent:'Evspor',dkd_score:'2:1',dkd_venue:'away',dkd_result:'L'},{dkd_date:'14.09.2026',dkd_opponent:'Rakip C',dkd_score:'0:0',dkd_venue:'home',dkd_result:'D'},{dkd_date:'09.09.2026',dkd_opponent:'Rakip D',dkd_score:'1:2',dkd_venue:'home',dkd_result:'L'}]}};

dkd_test('Plain Turkish reason uses concrete form, scores, standings and verified context',()=>{const dkd_text=dkd_friendlyReason(dkd_match,dkd_match.dkd_markets[0]!,dkd_context);dkd_assert.match(dkd_text,/Son form:/i);dkd_assert.match(dkd_text,/Son skorlar:/i);dkd_assert.match(dkd_text,/Deplasman SK karşısında 2-1 kazandı/i);dkd_assert.match(dkd_text,/Lig durumu:/i);dkd_assert.match(dkd_text,/Evspor 3\. sırada ve 20 puanda/i);dkd_assert.match(dkd_text,/önceki maçları/i);dkd_assert.match(dkd_text,/Evspor galibiyeti yaklaşık %52/i);dkd_assert.match(dkd_text,/Deplasman SK galibiyeti %20/i);dkd_assert.match(dkd_text,/Kadro:/i);dkd_assert.match(dkd_text,/Seçim nedeni:/i);dkd_assert.match(dkd_text,/kesin sonuç veya kazanç garantisi değildir/i);});

dkd_test('Missing team context is explained without old technical wording or invented form',()=>{const dkd_text=dkd_friendlyReason(dkd_match,dkd_match.dkd_markets[2]!,null);dkd_assert.match(dkd_text,/doğrulanmış son maç, lig sırası veya kadro verisi bulunamadı/i);dkd_assert.match(dkd_text,/yalnızca mevcut güncel oran ve hesaplanan yaklaşık gerçekleşme yüzdesine göre/i);dkd_assert.doesNotMatch(dkd_text,/uydurma form bilgisi/i);dkd_assert.doesNotMatch(dkd_text,/bahis şirketinin payı çıkarıldıktan sonra/i);dkd_assert.doesNotMatch(dkd_text,/son 5 maçta/i);});
