import dkd_test from 'node:test';
import dkd_assert from 'node:assert/strict';
import { dkd_marketInsight, dkd_rankAnalysisMarkets } from '../src/dkd-analysis';
import type { dkd_Match } from '../src/dkd-types';

const dkd_match:dkd_Match={dkd_id:'dbo_analysis',dkd_league:'Test Lig',dkd_country:'Türkiye',dkd_color:'#B6F36A',dkd_home:{dkd_id:'dkd_home',dkd_name:'Ev Takımı',dkd_short:'EV',dkd_color:'#B6F36A',dkd_attack:1,dkd_defense:1,dkd_form:[]},dkd_away:{dkd_id:'dkd_away',dkd_name:'Deplasman',dkd_short:'DEP',dkd_color:'#6DBFFF',dkd_attack:1,dkd_defense:1,dkd_form:[]},dkd_offset:0,dkd_time:'20:00',dkd_startAt:new Date().toISOString(),dkd_sourceCount:1,dkd_quality:.76,dkd_explanation:'Teknik kaynak açıklaması görünür gerekçe olmamalı.',dkd_lastSeenAt:new Date().toISOString(),dkd_venue:'',dkd_temperature:0,dkd_weather:'',dkd_xgHome:0,dkd_xgAway:0,dkd_markets:[{dkd_key:'home',dkd_label:'Maç sonucu 1',dkd_short:'MS 1',dkd_odds:2.4,dkd_probability:.39,dkd_group:'Maç sonucu'},{dkd_key:'draw',dkd_label:'Maç sonucu X',dkd_short:'MS X',dkd_odds:3.1,dkd_probability:.30,dkd_group:'Maç sonucu'},{dkd_key:'away',dkd_label:'Maç sonucu 2',dkd_short:'MS 2',dkd_odds:3.4,dkd_probability:.31,dkd_group:'Maç sonucu'},{dkd_key:'dbo:total_goals|over|3.5',dkd_label:'3,5 Üst',dkd_short:'3,5 Ü',dkd_odds:1.06,dkd_probability:.78,dkd_group:'Toplam gol'}],dkd_history:[],dkd_absences:[0,0],dkd_rest:[0,0]};

dkd_test('Analysis ranking balances probability with price instead of blindly picking shortest odds',()=>{const dkd_ranked=dkd_rankAnalysisMarkets(dkd_match);dkd_assert.ok(dkd_ranked.length===4);dkd_assert.notEqual(dkd_ranked[0]!.dkd_label,'3,5 Üst');});
dkd_test('Market insight explains selection with readable Turkish wording',()=>{const dkd_top=dkd_rankAnalysisMarkets(dkd_match)[0]!,dkd_insight=dkd_marketInsight(dkd_match,dkd_top),dkd_text=dkd_insight.dkd_points.join(' ');dkd_assert.ok(dkd_insight.dkd_score>0);dkd_assert.ok(dkd_insight.dkd_rank>=1);dkd_assert.match(dkd_text,/Güncel oran:/i);dkd_assert.match(dkd_text,/Ev Takımı.*Deplasman/i);dkd_assert.match(dkd_text,/yaklaşık gerçekleşme/i);dkd_assert.match(dkd_text,/Seçim nedeni:/i);dkd_assert.match(dkd_text,/Karşılaştırma:/i);dkd_assert.match(dkd_text,/kesin sonuç/i);dkd_assert.doesNotMatch(dkd_text,/bahis şirketinin payı çıkarıldıktan sonra/i);dkd_assert.doesNotMatch(dkd_text,/oran kaynağı/i);});
