import * as dkd_React from 'react';
import * as dkd_RN from 'react-native';
import * as dkd_Router from 'expo-router';
import { dkd, dkd_colors } from '../../src/dkd-ui';
import { dkd_dateFromIso } from '../../src/dkd-live';
import { dkd_getMarket, dkd_decimal, dkd_percent } from '../../src/dkd-engine';
import { dkd_useStore } from '../../src/dkd-store';

export default function dkd_MatchScreen(){
  const {dkd_id}=dkd_Router.useLocalSearchParams<{dkd_id:string}>();const dkd_store=dkd_useStore();const [dkd_tab,dkd_setTab]=dkd_React.useState('overview');const dkd_match=dkd_store.dkd_matches.find(dkd_item=>dkd_item.dkd_id===dkd_id)??dkd_store.dkd_stored.dkd_coupons.flatMap(dkd_coupon=>dkd_coupon.dkd_snapshot).find(dkd_item=>dkd_item.dkd_id===dkd_id);
  if(!dkd_match)return <dkd.Page><dkd.Empty dkd_title="Maç bulunamadı" dkd_body="Bu karşılaşma güncel fikstürde veya kayıtlı raporlarda bulunmuyor." dkd_action="Maç merkezine dön" dkd_onPress={()=>dkd_Router.router.replace('/matches')}/></dkd.Page>;
  const dkd_favorite=dkd_store.dkd_stored.dkd_favorites.includes(dkd_match.dkd_id),dkd_ready=dkd_match.dkd_markets.length>=3,dkd_groups=[...new Set(dkd_match.dkd_markets.map(dkd_market=>dkd_market.dkd_group||'Diğer'))];
  const dkd_header=<><dkd_Router.Stack.Screen options={{title:dkd_match.dkd_home.dkd_short+' – '+dkd_match.dkd_away.dkd_short,headerRight:()=> <dkd.IconButton dkd_label={dkd_favorite?'Favoriden çıkar':'Favorilere ekle'} dkd_icon="star" dkd_color={dkd_favorite?dkd_colors.yellow:dkd_colors.muted} dkd_active={dkd_favorite} dkd_onPress={()=>dkd_store.dkd_toggleFavorite(dkd_match.dkd_id)}/>}}/><dkd.Reveal><dkd.Card dkd_style={{gap:20,borderColor:dkd_match.dkd_color+'60'}}><dkd.Row dkd_between><dkd.Badge dkd_color={dkd_match.dkd_color}>{dkd_match.dkd_league.toLocaleUpperCase('tr-TR')}</dkd.Badge><dkd.Text dkd_size={11} dkd_color={dkd_ready?dkd_colors.lime:dkd_colors.blue} dkd_bold>{dkd_ready?`${dkd_match.dkd_markets.length} ORAN HAZIR`:'FİKSTÜR HAZIR'}</dkd.Text></dkd.Row><dkd.Row dkd_between dkd_style={{alignItems:'flex-start'}}><dkd_RN.View style={{flex:1,alignItems:'center',gap:10}}><dkd.Crest dkd_team={dkd_match.dkd_home} dkd_size={64}/><dkd.Text dkd_bold dkd_style={{textAlign:'center'}}>{dkd_match.dkd_home.dkd_name}</dkd.Text></dkd_RN.View><dkd_RN.View style={{alignItems:'center',paddingTop:12,gap:5}}><dkd.Text dkd_size={24} dkd_bold>{dkd_match.dkd_time}</dkd.Text><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_dateFromIso(dkd_match.dkd_startAt)}</dkd.Text></dkd_RN.View><dkd_RN.View style={{flex:1,alignItems:'center',gap:10}}><dkd.Crest dkd_team={dkd_match.dkd_away} dkd_size={64}/><dkd.Text dkd_bold dkd_style={{textAlign:'center'}}>{dkd_match.dkd_away.dkd_name}</dkd.Text></dkd_RN.View></dkd.Row><dkd.Row><dkd.Icon dkd_name="calendar" dkd_size={17} dkd_color={dkd_colors.muted}/><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>{dkd_dateFromIso(dkd_match.dkd_startAt,true)} · TSİ {dkd_match.dkd_time}</dkd.Text></dkd.Row></dkd.Card></dkd.Reveal></>;
  if(!dkd_ready)return <dkd.Page>{dkd_header}<dkd.Card dkd_style={{borderColor:'#334C66'}}><dkd.Row><dkd.Icon dkd_name="check" dkd_color={dkd_colors.blue}/><dkd.Text dkd_size={20} dkd_bold>Gerçek fikstür yüklendi</dkd.Text></dkd.Row><dkd.Text dkd_color={dkd_colors.muted}>Bu karşılaşmanın tarihi ve takımları güncel fikstür kaynağından geldi. Doğrulanmış oran marketi henüz bulunmadığı için analiz ve kupon alanları kapalı.</dkd.Text><dkd.Button dkd_label="Oranları yeniden kontrol et" dkd_icon="refresh" dkd_variant="secondary" dkd_onPress={()=>dkd_store.dkd_refreshLive()}/></dkd.Card><dkd.Notice dkd_text="DraBornOdds eksik oranı tahmin ederek doldurmaz. Doğrulanmış marketler geldiğinde bu ekran otomatik olarak analiz görünümüne geçer."/></dkd.Page>;
  const dkd_top=[...dkd_match.dkd_markets].sort((dkd_a,dkd_b)=>dkd_b.dkd_probability-dkd_a.dkd_probability)[0]!,dkd_home=dkd_getMarket(dkd_match,'home'),dkd_draw=dkd_getMarket(dkd_match,'draw'),dkd_away=dkd_getMarket(dkd_match,'away'),dkd_quality=Math.round(dkd_match.dkd_quality*100);
  return <dkd.Page>{dkd_header}
    <dkd.Chips dkd_options={[{dkd_id:'overview',dkd_label:'Genel bakış'},{dkd_id:'stats',dkd_label:'Veri kalitesi'},{dkd_id:'odds',dkd_label:'Tüm oranlar'}]} dkd_value={dkd_tab} dkd_onChange={dkd_setTab}/>
    {dkd_tab==='overview'&&<><dkd.Card dkd_style={{borderColor:'#3D5130'}}><dkd.Row dkd_between><dkd.Badge dkd_icon="spark">YÜKSEK PİYASA OLASILIĞI</dkd.Badge><dkd.Text dkd_color={dkd_colors.lime} dkd_bold>{dkd_decimal(dkd_top.dkd_odds)}</dkd.Text></dkd.Row><dkd.Row><dkd_RN.View style={{flex:1,gap:7}}><dkd.Text dkd_size={21} dkd_bold>{dkd_top.dkd_label}</dkd.Text><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>{dkd_top.dkd_group} · marj-normalize/türetilmiş piyasa olasılığı</dkd.Text></dkd_RN.View><dkd.Ring dkd_value={dkd_top.dkd_probability} dkd_size={96}/></dkd.Row><dkd.Text dkd_size={13} dkd_color={dkd_colors.muted}>{dkd_match.dkd_explanation}</dkd.Text><dkd.Button dkd_label="Bu seçimi analize ekle" dkd_icon="plus" dkd_onPress={()=>dkd_store.dkd_select({dkd_matchId:dkd_match.dkd_id,dkd_marketKey:dkd_top.dkd_key})}/></dkd.Card><dkd.Section dkd_title="1 / X / 2 olasılık haritası" dkd_subtitle="Maç sonucu oranlarından bookmaker marjı normalize edilmiştir."/><dkd.Card><dkd_RN.View style={{flexDirection:'row',height:12,gap:3,borderRadius:10,overflow:'hidden'}}>{[dkd_home,dkd_draw,dkd_away].map((dkd_market,dkd_index)=><dkd_RN.View key={dkd_market.dkd_key} style={{flex:dkd_market.dkd_probability,backgroundColor:[dkd_colors.lime,dkd_colors.purple,dkd_colors.blue][dkd_index]}}/>)}</dkd_RN.View><dkd.Row dkd_between>{[dkd_home,dkd_draw,dkd_away].map((dkd_market,dkd_index)=><dkd_RN.View key={dkd_market.dkd_key} style={{gap:5}}><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_market.dkd_short}</dkd.Text><dkd.Text dkd_bold dkd_size={22} dkd_color={[dkd_colors.lime,dkd_colors.purple,dkd_colors.blue][dkd_index]}>{dkd_percent(dkd_market.dkd_probability)}</dkd.Text></dkd_RN.View>)}</dkd.Row></dkd.Card></>}
    {dkd_tab==='stats'&&<><dkd.Section dkd_title="Veri kalitesi" dkd_subtitle="Oran genişliği ve bağımsız kaynak sayısı kalite skoruna dahil edilir."/><dkd.Card><dkd.Row dkd_between><dkd.Text dkd_color={dkd_colors.muted}>Bağımsız oran kaynağı</dkd.Text><dkd.Text dkd_bold>{dkd_match.dkd_sourceCount}</dkd.Text></dkd.Row><dkd.Row dkd_between><dkd.Text dkd_color={dkd_colors.muted}>Market grubu</dkd.Text><dkd.Text dkd_bold>{dkd_groups.length}</dkd.Text></dkd.Row><dkd.Row dkd_between><dkd.Text dkd_color={dkd_colors.muted}>Doğrulanmış seçim</dkd.Text><dkd.Text dkd_bold>{dkd_match.dkd_markets.length}</dkd.Text></dkd.Row><dkd.Row dkd_between><dkd.Text dkd_color={dkd_colors.muted}>Kalite skoru</dkd.Text><dkd.Text dkd_bold dkd_color={dkd_quality>=70?dkd_colors.lime:dkd_colors.yellow}>%{dkd_quality}</dkd.Text></dkd.Row><dkd.Row dkd_between><dkd.Text dkd_color={dkd_colors.muted}>Son görülme</dkd.Text><dkd.Text dkd_size={12}>{new Date(dkd_match.dkd_lastSeenAt).toLocaleString('tr-TR')}</dkd.Text></dkd.Row></dkd.Card><dkd.Notice dkd_text="Analiz mevcut doğrulanmış oranları kullanır. Takım formu, sakatlık, hava ve xG gibi ayrı veri hatları doğrulanmadan sisteme uydurularak eklenmez."/></>}
    {dkd_tab==='odds'&&<>{dkd_groups.map(dkd_group=><dkd_RN.View key={dkd_group} style={{gap:10}}><dkd.Section dkd_title={dkd_group} dkd_subtitle={`${dkd_match.dkd_markets.filter(dkd_market=>(dkd_market.dkd_group||'Diğer')===dkd_group).length} doğrulanmış seçim`}/><dkd.Card>{dkd_match.dkd_markets.filter(dkd_market=>(dkd_market.dkd_group||'Diğer')===dkd_group).map(dkd_market=>{const dkd_selected=dkd_store.dkd_draft.some(dkd_pick=>dkd_pick.dkd_matchId===dkd_match.dkd_id&&dkd_pick.dkd_marketKey===dkd_market.dkd_key);return <dkd_RN.Pressable key={dkd_market.dkd_key} accessibilityRole="button" accessibilityState={{selected:dkd_selected}} accessibilityLabel={`${dkd_market.dkd_label} ${dkd_decimal(dkd_market.dkd_odds)}`} onPress={()=>dkd_store.dkd_select({dkd_matchId:dkd_match.dkd_id,dkd_marketKey:dkd_market.dkd_key})} style={{flexDirection:'row',alignItems:'center',gap:10,padding:12,borderRadius:13,backgroundColor:dkd_selected?'#25392A':dkd_colors.raised,borderWidth:1,borderColor:dkd_selected?dkd_colors.lime:'transparent'}}><dkd_RN.View style={{flex:1,gap:3}}><dkd.Text dkd_bold>{dkd_market.dkd_label}</dkd.Text><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_percent(dkd_market.dkd_probability)} piyasa olasılığı</dkd.Text></dkd_RN.View><dkd.Text dkd_size={20} dkd_bold dkd_color={dkd_colors.lime}>{dkd_decimal(dkd_market.dkd_odds)}</dkd.Text></dkd_RN.Pressable>;})}</dkd.Card></dkd_RN.View>)}</>}{dkd_store.dkd_draft.length>0&&<dkd.Button dkd_label={`Analizime git · ${dkd_store.dkd_draft.length} maç`} dkd_icon="ticket" dkd_onPress={()=>dkd_Router.router.push({pathname:'/builder',params:{dkd_mode:'manual'}})}/>}<dkd.Notice dkd_text="Olasılık kesinlik değildir. Oranlar değişebilir; rapor oluşturulduğunda o anki veri snapshot’ı saklanır."/>
  </dkd.Page>;
}
