import * as dkd_React from 'react';
import * as dkd_RN from 'react-native';
import * as dkd_Router from 'expo-router';
import { dkd, dkd_colors } from '../../src/dkd-ui';
import { dkd_dateFromIso, dkd_fetchMatchOdds } from '../../src/dkd-live';
import { dkd_getMarket, dkd_decimal, dkd_percent, dkd_modelMarkets } from '../../src/dkd-engine';
import { dkd_useStore } from '../../src/dkd-store';
import { dkd_fetchOddsMovement } from '../../src/dkd-movement';
import type { dkd_Movement } from '../../src/dkd-movement';
import type { dkd_Market } from '../../src/dkd-types';

export default function dkd_MatchScreen(){
  const {dkd_id}=dkd_Router.useLocalSearchParams<{dkd_id:string}>();const dkd_store=dkd_useStore();const [dkd_tab,dkd_setTab]=dkd_React.useState('overview');const [dkd_allOdds,dkd_setAllOdds]=dkd_React.useState<dkd_Market[]>([]);const [dkd_oddsBusy,dkd_setOddsBusy]=dkd_React.useState(false);const [dkd_oddsError,dkd_setOddsError]=dkd_React.useState('');const [dkd_movements,dkd_setMovements]=dkd_React.useState<dkd_Movement[]>([]);const [dkd_movementBusy,dkd_setMovementBusy]=dkd_React.useState(false);const [dkd_movementError,dkd_setMovementError]=dkd_React.useState('');const dkd_match=dkd_store.dkd_matches.find(dkd_item=>dkd_item.dkd_id===dkd_id)??dkd_store.dkd_stored.dkd_coupons.flatMap(dkd_coupon=>dkd_coupon.dkd_snapshot).find(dkd_item=>dkd_item.dkd_id===dkd_id);
  dkd_React.useEffect(()=>{let dkd_active=true;if(dkd_tab!=='odds'||!dkd_match||dkd_allOdds.length||dkd_oddsBusy)return()=>{dkd_active=false};dkd_setOddsBusy(true);dkd_setOddsError('');dkd_fetchMatchOdds(dkd_match.dkd_id).then(dkd_values=>{if(dkd_active)dkd_setAllOdds(dkd_values)}).catch(dkd_failure=>{if(dkd_active)dkd_setOddsError(dkd_failure instanceof Error?dkd_failure.message:'Tüm oranlar yüklenemedi.')}).finally(()=>{if(dkd_active)dkd_setOddsBusy(false)});return()=>{dkd_active=false};},[dkd_tab,dkd_match?.dkd_id,dkd_allOdds.length]);
  dkd_React.useEffect(()=>{let dkd_active=true;if(dkd_tab!=='movement'||!dkd_match||dkd_movements.length)return()=>{dkd_active=false};dkd_setMovementBusy(true);dkd_setMovementError('');dkd_fetchOddsMovement(dkd_match.dkd_id,6).then(dkd_values=>{if(dkd_active)dkd_setMovements(dkd_values)}).catch(dkd_failure=>{if(dkd_active)dkd_setMovementError(dkd_failure instanceof Error?dkd_failure.message:'Oran hareketi yüklenemedi.')}).finally(()=>{if(dkd_active)dkd_setMovementBusy(false)});return()=>{dkd_active=false};},[dkd_tab,dkd_match?.dkd_id,dkd_movements.length]);
  if(!dkd_match)return <dkd.Page><dkd.Empty dkd_title="Maç bulunamadı" dkd_body="Bu karşılaşma güncel fikstürde veya kayıtlı raporlarda bulunmuyor." dkd_action="Maç merkezine dön" dkd_onPress={()=>dkd_Router.router.replace('/matches')}/></dkd.Page>;
  const dkd_modelOdds=dkd_modelMarkets(dkd_match),dkd_favorite=dkd_store.dkd_stored.dkd_favorites.includes(dkd_match.dkd_id),dkd_ready=dkd_modelOdds.length>=3,dkd_visibleOdds=dkd_allOdds.length?dkd_allOdds:dkd_match.dkd_markets,dkd_groups=[...new Set(dkd_visibleOdds.map(dkd_market=>dkd_market.dkd_group||'Diğer'))];
  const dkd_header=<><dkd_Router.Stack.Screen options={{title:dkd_match.dkd_home.dkd_short+' – '+dkd_match.dkd_away.dkd_short,headerRight:()=> <dkd.IconButton dkd_label={dkd_favorite?'Favoriden çıkar':'Favorilere ekle'} dkd_icon="star" dkd_color={dkd_favorite?dkd_colors.yellow:dkd_colors.muted} dkd_active={dkd_favorite} dkd_onPress={()=>dkd_store.dkd_toggleFavorite(dkd_match.dkd_id)}/>}}/><dkd.Reveal><dkd.Card dkd_style={{gap:20,borderColor:dkd_match.dkd_color+'60'}}><dkd.Row dkd_between><dkd.Badge dkd_color={dkd_match.dkd_color}>{dkd_match.dkd_league.toLocaleUpperCase('tr-TR')}</dkd.Badge><dkd.Text dkd_size={11} dkd_color={dkd_ready?dkd_colors.lime:dkd_colors.blue} dkd_bold>{dkd_ready?`${dkd_modelOdds.length} ANALİZ ORANI`:'FİKSTÜR HAZIR'}</dkd.Text></dkd.Row><dkd.Row dkd_between dkd_style={{alignItems:'flex-start'}}><dkd_RN.View style={{flex:1,alignItems:'center',gap:10}}><dkd.Crest dkd_team={dkd_match.dkd_home} dkd_size={64}/><dkd.Text dkd_bold dkd_style={{textAlign:'center'}}>{dkd_match.dkd_home.dkd_name}</dkd.Text></dkd_RN.View><dkd_RN.View style={{alignItems:'center',paddingTop:12,gap:5}}><dkd.Text dkd_size={24} dkd_bold>{dkd_match.dkd_time}</dkd.Text><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_dateFromIso(dkd_match.dkd_startAt)}</dkd.Text></dkd_RN.View><dkd_RN.View style={{flex:1,alignItems:'center',gap:10}}><dkd.Crest dkd_team={dkd_match.dkd_away} dkd_size={64}/><dkd.Text dkd_bold dkd_style={{textAlign:'center'}}>{dkd_match.dkd_away.dkd_name}</dkd.Text></dkd_RN.View></dkd.Row><dkd.Row><dkd.Icon dkd_name="calendar" dkd_size={17} dkd_color={dkd_colors.muted}/><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>{dkd_dateFromIso(dkd_match.dkd_startAt,true)} · TSİ {dkd_match.dkd_time}</dkd.Text></dkd.Row></dkd.Card></dkd.Reveal></>;
  if(!dkd_ready)return <dkd.Page>{dkd_header}<dkd.Card dkd_style={{borderColor:'#334C66'}}><dkd.Row><dkd.Icon dkd_name="check" dkd_color={dkd_colors.blue}/><dkd.Text dkd_size={20} dkd_bold>Gerçek fikstür yüklendi</dkd.Text></dkd.Row><dkd.Text dkd_color={dkd_colors.muted}>Bu karşılaşmanın tarihi ve takımları güncel fikstür kaynağından geldi. Normalize edilebilir tam oran grubu henüz bulunmadığı için analiz ve kupon alanları kapalı.</dkd.Text><dkd.Button dkd_label="Oranları yeniden kontrol et" dkd_icon="refresh" dkd_variant="secondary" dkd_onPress={()=>dkd_store.dkd_refreshLive()}/></dkd.Card><dkd.Notice dkd_text="DraBornOdds eksik oranı tahmin ederek doldurmaz. Doğrulanmış tam marketler geldiğinde analiz otomatik açılır."/></dkd.Page>;
  const dkd_top=[...dkd_modelOdds].sort((dkd_a,dkd_b)=>dkd_b.dkd_probability-dkd_a.dkd_probability)[0]!,dkd_home=dkd_getMarket(dkd_match,'home'),dkd_draw=dkd_getMarket(dkd_match,'draw'),dkd_away=dkd_getMarket(dkd_match,'away'),dkd_quality=Math.round(dkd_match.dkd_quality*100),dkd_modelGroups=[...new Set(dkd_modelOdds.map(dkd_market=>dkd_market.dkd_group||'Diğer'))];
  return <dkd.Page>{dkd_header}
    <dkd.Chips dkd_options={[{dkd_id:'overview',dkd_label:'Genel bakış'},{dkd_id:'stats',dkd_label:'Veri kalitesi'},{dkd_id:'movement',dkd_label:'Oran hareketi'},{dkd_id:'odds',dkd_label:'Tüm oranlar'}]} dkd_value={dkd_tab} dkd_onChange={dkd_setTab}/>
    {dkd_tab==='overview'&&<><dkd.Card dkd_style={{borderColor:'#3D5130'}}><dkd.Row dkd_between><dkd.Badge dkd_icon="spark">YÜKSEK PİYASA OLASILIĞI</dkd.Badge><dkd.Text dkd_color={dkd_colors.lime} dkd_bold>{dkd_decimal(dkd_top.dkd_odds)}</dkd.Text></dkd.Row><dkd.Row><dkd_RN.View style={{flex:1,gap:7}}><dkd.Text dkd_size={21} dkd_bold>{dkd_top.dkd_label}</dkd.Text><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>{dkd_top.dkd_group} · marj-normalize/türetilmiş piyasa olasılığı</dkd.Text></dkd_RN.View><dkd.Ring dkd_value={dkd_top.dkd_probability} dkd_size={96}/></dkd.Row><dkd.Text dkd_size={13} dkd_color={dkd_colors.muted}>{dkd_match.dkd_explanation}</dkd.Text><dkd.Button dkd_label="Bu seçimi analize ekle" dkd_icon="plus" dkd_onPress={()=>dkd_store.dkd_select({dkd_matchId:dkd_match.dkd_id,dkd_marketKey:dkd_top.dkd_key})}/></dkd.Card><dkd.Section dkd_title="1 / X / 2 olasılık haritası" dkd_subtitle="Maç sonucu oranlarından bookmaker marjı normalize edilmiştir."/><dkd.Card><dkd_RN.View style={{flexDirection:'row',height:12,gap:3,borderRadius:10,overflow:'hidden'}}>{[dkd_home,dkd_draw,dkd_away].map((dkd_market,dkd_index)=><dkd_RN.View key={dkd_market.dkd_key} style={{flex:dkd_market.dkd_probability,backgroundColor:[dkd_colors.lime,dkd_colors.purple,dkd_colors.blue][dkd_index]}}/>)}</dkd_RN.View><dkd.Row dkd_between>{[dkd_home,dkd_draw,dkd_away].map((dkd_market,dkd_index)=><dkd_RN.View key={dkd_market.dkd_key} style={{gap:5}}><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_market.dkd_short}</dkd.Text><dkd.Text dkd_bold dkd_size={22} dkd_color={[dkd_colors.lime,dkd_colors.purple,dkd_colors.blue][dkd_index]}>{dkd_percent(dkd_market.dkd_probability)}</dkd.Text></dkd_RN.View>)}</dkd.Row></dkd.Card></>}
    {dkd_tab==='stats'&&<><dkd.Section dkd_title="Veri kalitesi" dkd_subtitle="Oran genişliği ve bağımsız kaynak sayısı kalite skoruna dahil edilir."/><dkd.Card><dkd.Row dkd_between><dkd.Text dkd_color={dkd_colors.muted}>Bağımsız oran kaynağı</dkd.Text><dkd.Text dkd_bold>{dkd_match.dkd_sourceCount}</dkd.Text></dkd.Row><dkd.Row dkd_between><dkd.Text dkd_color={dkd_colors.muted}>Normalize market ailesi</dkd.Text><dkd.Text dkd_bold>{dkd_modelGroups.length}</dkd.Text></dkd.Row><dkd.Row dkd_between><dkd.Text dkd_color={dkd_colors.muted}>Analize uygun seçim</dkd.Text><dkd.Text dkd_bold>{dkd_modelOdds.length}</dkd.Text></dkd.Row><dkd.Row dkd_between><dkd.Text dkd_color={dkd_colors.muted}>Kalite skoru</dkd.Text><dkd.Text dkd_bold dkd_color={dkd_quality>=70?dkd_colors.lime:dkd_colors.yellow}>%{dkd_quality}</dkd.Text></dkd.Row><dkd.Row dkd_between><dkd.Text dkd_color={dkd_colors.muted}>Son görülme</dkd.Text><dkd.Text dkd_size={12}>{new Date(dkd_match.dkd_lastSeenAt).toLocaleString('tr-TR')}</dkd.Text></dkd.Row></dkd.Card><dkd.Notice dkd_text="Kupon motoru yalnızca tüm karşılıklı sonuçları mevcut olan ve normalize edilebilen marketleri kullanır. Ham/eksik doğru skor veya ek market oranları görüntülenebilir fakat otomatik tahmine katılmaz."/></>}
    {dkd_tab==='movement'&&<><dkd.Section dkd_title="Son 6 saat · oran hareketi" dkd_subtitle="Aynı seçim için son 6 saatteki ilk/güncel collector snapshot oran farkı. Yön değişimi tek başına sonuç sinyali değildir."/>{dkd_movementBusy&&<dkd.Card><dkd.Text dkd_bold>Oran geçmişi yükleniyor…</dkd.Text></dkd.Card>}{!!dkd_movementError&&<dkd.Card dkd_style={{borderColor:dkd_colors.coral}}><dkd.Text dkd_color={dkd_colors.coral}>{dkd_movementError}</dkd.Text></dkd.Card>}{!dkd_movementBusy&&!dkd_movementError&&!dkd_movements.length&&<dkd.Empty dkd_title="Henüz hareket geçmişi yok" dkd_body="Bu maç için birden fazla collector snapshot’ı biriktiğinde oran hareketleri burada görünür."/>}{dkd_movements.slice(0,16).map(dkd_move=>{const dkd_up=dkd_move.dkd_delta>0,dkd_flat=Math.abs(dkd_move.dkd_delta)<.0001,dkd_color=dkd_flat?dkd_colors.muted:dkd_up?dkd_colors.blue:dkd_colors.coral,dkd_change=`${dkd_up?'+':''}${(dkd_move.dkd_deltaPct*100).toFixed(1).replace('.',',')}%`;return <dkd.Card key={dkd_move.dkd_id} dkd_style={{padding:14,gap:9}}><dkd.Row dkd_between><dkd_RN.View style={{flex:1,gap:3}}><dkd.Text dkd_bold>{dkd_move.dkd_label}</dkd.Text><dkd.Text dkd_size={10} dkd_color={dkd_colors.muted}>{dkd_move.dkd_samples} snapshot · min {dkd_decimal(dkd_move.dkd_min)} · max {dkd_decimal(dkd_move.dkd_max)}</dkd.Text></dkd_RN.View><dkd.Badge dkd_color={dkd_color}>{dkd_flat?'SABİT':dkd_up?'YÜKSELDİ':'DÜŞTÜ'} {dkd_change}</dkd.Badge></dkd.Row><dkd.Row dkd_between><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>İlk {dkd_decimal(dkd_move.dkd_open)}</dkd.Text><dkd.Text dkd_size={18} dkd_bold dkd_color={dkd_color}>Güncel {dkd_decimal(dkd_move.dkd_current)}</dkd.Text></dkd.Row></dkd.Card>})}<dkd.Notice dkd_text="Oran hareketi yalnızca piyasadaki fiyat değişimini gösterir; tek başına takım haberi, sonuç ihtimali veya bahis önerisi olarak yorumlanmaz."/></>}
    {dkd_tab==='odds'&&<>{dkd_oddsBusy&&<dkd.Card><dkd.Row><dkd.Icon dkd_name="refresh" dkd_color={dkd_colors.blue}/><dkd.Text dkd_bold>Tüm kazınmış oranlar yükleniyor…</dkd.Text></dkd.Row></dkd.Card>}{!!dkd_oddsError&&<dkd.Card dkd_style={{borderColor:dkd_colors.coral}}><dkd.Text dkd_color={dkd_colors.coral}>{dkd_oddsError}</dkd.Text></dkd.Card>}{dkd_groups.map(dkd_group=><dkd_RN.View key={dkd_group} style={{gap:10}}><dkd.Section dkd_title={dkd_group} dkd_subtitle={`${dkd_visibleOdds.filter(dkd_market=>(dkd_market.dkd_group||'Diğer')===dkd_group).length} oran`}/><dkd.Card>{dkd_visibleOdds.filter(dkd_market=>(dkd_market.dkd_group||'Diğer')===dkd_group).map((dkd_market,dkd_index)=>{const dkd_selectable=dkd_market.dkd_modelEligible!==false&&dkd_match.dkd_markets.some(dkd_value=>dkd_value.dkd_key===dkd_market.dkd_key),dkd_selected=dkd_store.dkd_draft.some(dkd_pick=>dkd_pick.dkd_matchId===dkd_match.dkd_id&&dkd_pick.dkd_marketKey===dkd_market.dkd_key);return <dkd_RN.Pressable key={`${dkd_market.dkd_key}_${dkd_index}`} accessibilityRole={dkd_selectable?'button':'text'} accessibilityState={dkd_selectable?{selected:dkd_selected}:undefined} accessibilityLabel={`${dkd_market.dkd_label} ${dkd_decimal(dkd_market.dkd_odds)}`} disabled={!dkd_selectable} onPress={()=>dkd_store.dkd_select({dkd_matchId:dkd_match.dkd_id,dkd_marketKey:dkd_market.dkd_key})} style={{flexDirection:'row',alignItems:'center',gap:10,padding:12,borderRadius:13,backgroundColor:dkd_selected?'#25392A':dkd_colors.raised,borderWidth:1,borderColor:dkd_selected?dkd_colors.lime:'transparent'}}><dkd_RN.View style={{flex:1,gap:3}}><dkd.Text dkd_bold>{dkd_market.dkd_label}</dkd.Text><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_selectable?`${dkd_percent(dkd_market.dkd_probability)} normalize piyasa olasılığı`:'Kazınmış ham oran · eksik/örtüşen market olduğu için kupon modeline kapalı'}</dkd.Text></dkd_RN.View><dkd.Text dkd_size={20} dkd_bold dkd_color={dkd_selectable?dkd_colors.lime:dkd_colors.text}>{dkd_decimal(dkd_market.dkd_odds)}</dkd.Text></dkd_RN.Pressable>;})}</dkd.Card></dkd_RN.View>)}</>}{dkd_store.dkd_draft.length>0&&<dkd.Button dkd_label={`Analizime git · ${dkd_store.dkd_draft.length} maç`} dkd_icon="ticket" dkd_onPress={()=>dkd_Router.router.push({pathname:'/builder',params:{dkd_mode:'manual'}})}/>}<dkd.Notice dkd_text="Olasılık kesinlik değildir. Oranlar değişebilir; rapor oluşturulduğunda o anki veri snapshot’ı saklanır."/>
  </dkd.Page>;
}
