import * as dkd_React from 'react';
import * as dkd_RN from 'react-native';
import * as dkd_Router from 'expo-router';
import { dkd, dkd_colors } from '../../src/dkd-ui';
import { dkd_dateFromIso, dkd_fetchMatchOdds } from '../../src/dkd-live';
import { dkd_decimal, dkd_modelMarkets, dkd_percent } from '../../src/dkd-engine';
import { dkd_marketInsight, dkd_rankAnalysisMarkets } from '../../src/dkd-analysis';
import { dkd_fetchMatchContext, type dkd_MatchContext } from '../../src/dkd-football-context';
import { dkd_TeamLogo } from '../../src/dkd-team-logo';
import { dkd_useStore } from '../../src/dkd-store';
import { dkd_fetchOddsMovement } from '../../src/dkd-movement';
import type { dkd_Movement } from '../../src/dkd-movement';
import type { dkd_Market } from '../../src/dkd-types';

const dkd_components={TeamLogo:dkd_TeamLogo,Row:dkd_Row};

export default function dkd_MatchScreen(){
  const {dkd_id}=dkd_Router.useLocalSearchParams<{dkd_id:string}>();
  const dkd_store=dkd_useStore();
  const [dkd_tab,dkd_setTab]=dkd_React.useState('overview');
  const [dkd_allOdds,dkd_setAllOdds]=dkd_React.useState<dkd_Market[]>([]),[dkd_oddsBusy,dkd_setOddsBusy]=dkd_React.useState(false),[dkd_oddsError,dkd_setOddsError]=dkd_React.useState('');
  const [dkd_movements,dkd_setMovements]=dkd_React.useState<dkd_Movement[]>([]),[dkd_movementBusy,dkd_setMovementBusy]=dkd_React.useState(false),[dkd_movementError,dkd_setMovementError]=dkd_React.useState('');
  const [dkd_context,dkd_setContext]=dkd_React.useState<dkd_MatchContext|null>(null);
  const dkd_match=dkd_store.dkd_matches.find(dkd_item=>dkd_item.dkd_id===dkd_id)??dkd_store.dkd_stored.dkd_coupons.flatMap(dkd_coupon=>dkd_coupon.dkd_snapshot).find(dkd_item=>dkd_item.dkd_id===dkd_id);
  dkd_React.useEffect(()=>{let dkd_active=true;dkd_setContext(null);if(!dkd_match)return()=>{dkd_active=false};dkd_fetchMatchContext(dkd_match).then(dkd_value=>{if(dkd_active)dkd_setContext(dkd_value)});return()=>{dkd_active=false};},[dkd_match?.dkd_id]);
  dkd_React.useEffect(()=>{let dkd_active=true;if(dkd_tab!=='odds'||!dkd_match||dkd_allOdds.length||dkd_oddsBusy)return()=>{dkd_active=false};dkd_setOddsBusy(true);dkd_setOddsError('');dkd_fetchMatchOdds(dkd_match.dkd_id).then(dkd_values=>{if(dkd_active)dkd_setAllOdds(dkd_values)}).catch(dkd_failure=>{if(dkd_active)dkd_setOddsError(dkd_failure instanceof Error?dkd_failure.message:'Tüm oranlar yüklenemedi.')}).finally(()=>{if(dkd_active)dkd_setOddsBusy(false)});return()=>{dkd_active=false};},[dkd_tab,dkd_match?.dkd_id,dkd_allOdds.length,dkd_oddsBusy]);
  dkd_React.useEffect(()=>{let dkd_active=true;if(dkd_tab!=='movement'||!dkd_match||dkd_movements.length||dkd_movementBusy)return()=>{dkd_active=false};dkd_setMovementBusy(true);dkd_setMovementError('');dkd_fetchOddsMovement(dkd_match.dkd_id,6).then(dkd_values=>{if(dkd_active)dkd_setMovements(dkd_values)}).catch(dkd_failure=>{if(dkd_active)dkd_setMovementError(dkd_failure instanceof Error?dkd_failure.message:'Oran hareketi yüklenemedi.')}).finally(()=>{if(dkd_active)dkd_setMovementBusy(false)});return()=>{dkd_active=false};},[dkd_tab,dkd_match?.dkd_id,dkd_movements.length,dkd_movementBusy]);
  if(!dkd_match)return <dkd.Page><dkd.Empty dkd_title="Maç bulunamadı" dkd_body="Bu karşılaşma güncel fikstürde veya kayıtlı raporlarda bulunmuyor." dkd_action="Maç merkezine dön" dkd_onPress={()=>dkd_Router.router.replace('/matches')}/></dkd.Page>;
  const dkd_markets=dkd_modelMarkets(dkd_match),dkd_ranked=dkd_rankAnalysisMarkets(dkd_match),dkd_ready=dkd_ranked.length>0,dkd_top=dkd_ranked[0],dkd_insight=dkd_top?dkd_marketInsight(dkd_match,dkd_top,dkd_context):null;
  const dkd_favorite=dkd_store.dkd_stored.dkd_favorites.includes(dkd_match.dkd_id),dkd_accent=dkd_match.dkd_color||dkd_colors.lime,dkd_visibleOdds=dkd_allOdds.length?dkd_allOdds:dkd_match.dkd_markets;
  const dkd_home=dkd_markets.find(dkd_market=>dkd_market.dkd_key==='home'),dkd_draw=dkd_markets.find(dkd_market=>dkd_market.dkd_key==='draw'),dkd_away=dkd_markets.find(dkd_market=>dkd_market.dkd_key==='away');
  const dkd_header=<><dkd_Router.Stack.Screen options={{title:dkd_match.dkd_home.dkd_short+' – '+dkd_match.dkd_away.dkd_short,headerRight:()=> <dkd.IconButton dkd_label={dkd_favorite?'Favoriden çıkar':'Favorilere ekle'} dkd_icon="star" dkd_color={dkd_favorite?dkd_colors.yellow:dkd_colors.muted} dkd_active={dkd_favorite} dkd_onPress={()=>dkd_store.dkd_toggleFavorite(dkd_match.dkd_id)}/>}}/><dkd.Reveal><dkd_RN.View style={{borderRadius:25,overflow:'hidden',backgroundColor:dkd_colors.card,borderWidth:1,borderColor:dkd_accent+'65'}}><dkd_RN.View style={{height:4,backgroundColor:dkd_accent}}/><dkd_RN.View style={{padding:18,gap:18}}><dkd.Row dkd_between><dkd.Badge dkd_color={dkd_accent} dkd_icon="ball">{dkd_match.dkd_league.toLocaleUpperCase('tr-TR')}</dkd.Badge><dkd.Text dkd_size={11} dkd_color={dkd_ready?dkd_colors.lime:dkd_colors.blue} dkd_bold>{dkd_ready?`${dkd_ranked.length} ANALİZ SEÇİMİ`:'FİKSTÜR HAZIR'}</dkd.Text></dkd.Row><dkd.Row dkd_between dkd_style={{alignItems:'center'}}><dkd_RN.View style={{flex:1,alignItems:'center',gap:9}}><dkd_components.TeamLogo dkd_team={dkd_match.dkd_home} dkd_size={70}/><dkd.Text dkd_size={13} dkd_bold dkd_lines={2} dkd_style={{textAlign:'center'}}>{dkd_match.dkd_home.dkd_name}</dkd.Text></dkd_RN.View><dkd_RN.View style={{alignItems:'center',gap:5,paddingHorizontal:9}}><dkd.Text dkd_size={26} dkd_bold>{dkd_match.dkd_time}</dkd.Text><dkd.Text dkd_size={10} dkd_color={dkd_colors.muted}>{dkd_dateFromIso(dkd_match.dkd_startAt)}</dkd.Text><dkd.Badge dkd_color={dkd_colors.muted}>VS</dkd.Badge></dkd_RN.View><dkd_RN.View style={{flex:1,alignItems:'center',gap:9}}><dkd_components.TeamLogo dkd_team={dkd_match.dkd_away} dkd_size={70}/><dkd.Text dkd_size={13} dkd_bold dkd_lines={2} dkd_style={{textAlign:'center'}}>{dkd_match.dkd_away.dkd_name}</dkd.Text></dkd_RN.View></dkd.Row><dkd.Row><dkd.Icon dkd_name="calendar" dkd_size={16} dkd_color={dkd_colors.muted}/><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_dateFromIso(dkd_match.dkd_startAt,true)} · TSİ {dkd_match.dkd_time}</dkd.Text></dkd.Row></dkd_RN.View></dkd_RN.View></dkd.Reveal></>;
  if(!dkd_ready)return <dkd.Page>{dkd_header}<dkd.Card dkd_style={{borderColor:dkd_colors.blue+'55'}}><dkd.Row><dkd.Icon dkd_name="check" dkd_color={dkd_colors.blue}/><dkd.Text dkd_size={20} dkd_bold>Gerçek fikstür hazır</dkd.Text></dkd.Row><dkd.Text dkd_color={dkd_colors.muted}>Bu karşılaşma gerçek fikstürde doğrulandı. Karşılıklı sonuçları eksiksiz doğrulanmış bir oran grubu gelmeden analiz üretmiyoruz.</dkd.Text><dkd.Button dkd_label="Oranları yeniden kontrol et" dkd_icon="refresh" dkd_variant="secondary" dkd_onPress={()=>dkd_store.dkd_refreshLive()}/></dkd.Card><dkd.Notice dkd_text="Eksik oran, takım formu veya istatistik tahmin edilerek doldurulmaz; doğrulanan veri geldikçe analiz otomatik genişler."/></dkd.Page>;
  return <dkd.Page>{dkd_header}
    <dkd.Chips dkd_options={[{dkd_id:'overview',dkd_label:'Genel bakış'},{dkd_id:'analysis',dkd_label:'Neden bu seçim?'},{dkd_id:'movement',dkd_label:'Oran hareketi'},{dkd_id:'odds',dkd_label:'Tüm oranlar'}]} dkd_value={dkd_tab} dkd_onChange={dkd_setTab}/>
    {dkd_tab==='overview'&&dkd_top&&dkd_insight&&<><dkd.Card dkd_style={{borderColor:dkd_colors.lime+'55',gap:16}}><dkd.Row dkd_between><dkd.Badge dkd_icon="spark">ÖNE ÇIKAN ANALİZ</dkd.Badge><dkd_RN.View style={{alignItems:'flex-end'}}><dkd.Text dkd_size={10} dkd_color={dkd_colors.muted}>Güncel oran</dkd.Text><dkd.Text dkd_size={22} dkd_color={dkd_colors.lime} dkd_bold>{dkd_decimal(dkd_top.dkd_odds)}</dkd.Text></dkd_RN.View></dkd.Row><dkd.Row dkd_style={{alignItems:'center'}}><dkd_RN.View style={{flex:1,gap:6}}><dkd.Text dkd_size={22} dkd_bold>{dkd_top.dkd_label}</dkd.Text><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_top.dkd_group} · olasılık + oran dengesi</dkd.Text><dkd.Row dkd_gap={7}><dkd.Badge dkd_color={dkd_colors.blue}>{dkd_insight.dkd_score}/100 DENGE</dkd.Badge><dkd.Badge dkd_color={dkd_colors.purple}>#{dkd_insight.dkd_rank} SIRA</dkd.Badge></dkd.Row></dkd_RN.View><dkd.Ring dkd_value={dkd_top.dkd_probability} dkd_size={94} dkd_label="Normalize piyasa olasılığı"/></dkd.Row><dkd_RN.View style={{padding:13,borderRadius:15,backgroundColor:dkd_colors.lime+'0D',borderWidth:1,borderColor:dkd_colors.lime+'2D'}}><dkd.Text dkd_size={12} dkd_bold dkd_color={dkd_colors.lime}>NEDEN ÖNE ÇIKTI?</dkd.Text><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted} dkd_style={{marginTop:5}}>{dkd_insight.dkd_points[0]}</dkd.Text></dkd_RN.View><dkd.Button dkd_label="Bu seçimi analize ekle" dkd_icon="plus" dkd_onPress={()=>dkd_store.dkd_select({dkd_matchId:dkd_match.dkd_id,dkd_marketKey:dkd_top.dkd_key})}/></dkd.Card>{dkd_home&&dkd_draw&&dkd_away&&<><dkd.Section dkd_title="1 / X / 2 olasılık haritası" dkd_subtitle="Karşılıklı maç sonucu oranlarından bookmaker marjı çıkarıldı."/><dkd.Card><dkd_RN.View style={{flexDirection:'row',height:12,gap:3,borderRadius:10,overflow:'hidden'}}>{[dkd_home,dkd_draw,dkd_away].map((dkd_market,dkd_index)=><dkd_RN.View key={dkd_market.dkd_key} style={{flex:dkd_market.dkd_probability,backgroundColor:[dkd_colors.lime,dkd_colors.purple,dkd_colors.blue][dkd_index]}}/>)}</dkd_RN.View><dkd.Row dkd_between>{[dkd_home,dkd_draw,dkd_away].map((dkd_market,dkd_index)=><dkd_RN.View key={dkd_market.dkd_key} style={{gap:4}}><dkd.Text dkd_size={10} dkd_color={dkd_colors.muted}>{dkd_market.dkd_short}</dkd.Text><dkd.Text dkd_bold dkd_size={21} dkd_color={[dkd_colors.lime,dkd_colors.purple,dkd_colors.blue][dkd_index]}>{dkd_percent(dkd_market.dkd_probability)}</dkd.Text></dkd_RN.View>)}</dkd.Row></dkd.Card></>}</>}
    {dkd_tab==='analysis'&&dkd_top&&dkd_insight&&<><dkd.Section dkd_title="Seçim mantığı" dkd_subtitle="Takımların son dönem performansı, karşılaşma dengesi ve güncel oran ilişkisini kısa ve anlaşılır biçimde açıklar."/><dkd.Card dkd_style={{gap:12}}><dkd.Row dkd_between><dkd_RN.View style={{flex:1}}><dkd.Text dkd_size={18} dkd_bold>{dkd_top.dkd_label}</dkd.Text><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_top.dkd_group}</dkd.Text></dkd_RN.View><dkd.Badge dkd_color={dkd_colors.lime}>{dkd_decimal(dkd_top.dkd_odds)}</dkd.Badge></dkd.Row>{dkd_insight.dkd_points.map((dkd_point,dkd_index)=><dkd_RN.View key={dkd_index} style={{flexDirection:'row',gap:10,alignItems:'flex-start',padding:12,borderRadius:14,backgroundColor:[dkd_colors.blue,dkd_colors.lime,dkd_colors.purple,dkd_colors.yellow][dkd_index]+'0C'}}><dkd_RN.View style={{width:25,height:25,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:[dkd_colors.blue,dkd_colors.lime,dkd_colors.purple,dkd_colors.yellow][dkd_index]+'22'}}><dkd.Text dkd_size={10} dkd_bold dkd_color={[dkd_colors.blue,dkd_colors.lime,dkd_colors.purple,dkd_colors.yellow][dkd_index]}>{dkd_index+1}</dkd.Text></dkd_RN.View><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted} dkd_style={{flex:1}}>{dkd_point}</dkd.Text></dkd_RN.View>)}</dkd.Card><dkd.Section dkd_title="Hesabın özeti"/><dkd.Card dkd_style={{gap:10}}><dkd_components.Row dkd_label="Normalize olasılık" dkd_value={dkd_percent(dkd_insight.dkd_probability)} dkd_color={dkd_colors.lime}/><dkd_components.Row dkd_label="Oranın ham ima ettiği" dkd_value={dkd_percent(dkd_insight.dkd_implied)} dkd_color={dkd_colors.blue}/><dkd_components.Row dkd_label="Olasılık–oran dengesi" dkd_value={`${dkd_insight.dkd_score}/100`} dkd_color={dkd_colors.purple}/><dkd_components.Row dkd_label="Maç içi sıralama" dkd_value={`${dkd_insight.dkd_rank}/${dkd_insight.dkd_total}`} dkd_color={dkd_colors.yellow}/></dkd.Card><dkd.Notice dkd_text="Bu açıklama sonuç garantisi değildir. Piyasa-normalize olasılık, doğrulanmış oranların birbirine göre fiyatlamasını anlatır; takım performansı verisi doğrulanmadıkça analiz gerekçesine eklenmez."/></>}
    {dkd_tab==='movement'&&<><dkd.Section dkd_title="Son 6 saat · oran hareketi" dkd_subtitle="Fiyat değişimi ayrıca izlenir; tek başına sonuç sinyali sayılmaz."/>{dkd_movementBusy&&<dkd.Card><dkd.Text dkd_bold>Oran geçmişi yükleniyor…</dkd.Text></dkd.Card>}{!!dkd_movementError&&<dkd.Card dkd_style={{borderColor:dkd_colors.coral}}><dkd.Text dkd_color={dkd_colors.coral}>{dkd_movementError}</dkd.Text></dkd.Card>}{!dkd_movementBusy&&!dkd_movementError&&!dkd_movements.length&&<dkd.Empty dkd_title="Henüz hareket geçmişi yok" dkd_body="Birden fazla oran snapshot’ı biriktiğinde fiyat hareketleri burada görünür."/>}{dkd_movements.slice(0,16).map(dkd_move=>{const dkd_up=dkd_move.dkd_delta>0,dkd_flat=Math.abs(dkd_move.dkd_delta)<.0001,dkd_color=dkd_flat?dkd_colors.muted:dkd_up?dkd_colors.blue:dkd_colors.coral;return <dkd.Card key={dkd_move.dkd_id} dkd_style={{padding:14,gap:8}}><dkd.Row dkd_between><dkd_RN.View style={{flex:1}}><dkd.Text dkd_bold>{dkd_move.dkd_label}</dkd.Text><dkd.Text dkd_size={10} dkd_color={dkd_colors.muted}>{dkd_move.dkd_samples} snapshot · min {dkd_decimal(dkd_move.dkd_min)} · max {dkd_decimal(dkd_move.dkd_max)}</dkd.Text></dkd_RN.View><dkd.Badge dkd_color={dkd_color}>{dkd_flat?'SABİT':dkd_up?'YÜKSELDİ':'DÜŞTÜ'}</dkd.Badge></dkd.Row><dkd.Row dkd_between><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>İlk {dkd_decimal(dkd_move.dkd_open)}</dkd.Text><dkd.Text dkd_size={18} dkd_bold dkd_color={dkd_color}>Güncel {dkd_decimal(dkd_move.dkd_current)}</dkd.Text></dkd.Row></dkd.Card>})}</>}
    {dkd_tab==='odds'&&<>{dkd_oddsBusy&&<dkd.Card><dkd.Text dkd_bold>Tüm oranlar yükleniyor…</dkd.Text></dkd.Card>}{!!dkd_oddsError&&<dkd.Card dkd_style={{borderColor:dkd_colors.coral}}><dkd.Text dkd_color={dkd_colors.coral}>{dkd_oddsError}</dkd.Text></dkd.Card>}<dkd.Section dkd_title="Doğrulanmış oranlar" dkd_subtitle={`${dkd_visibleOdds.length} güncel seçim; analiz için tamamlanmış karşılıklı marketler ayrıca işaretlenir.`}/>{dkd_visibleOdds.map((dkd_market,dkd_index)=>{const dkd_eligible=dkd_market.dkd_modelEligible!==false;return <dkd.Card key={`${dkd_market.dkd_key}_${dkd_index}`} dkd_style={{padding:13,gap:7,borderColor:dkd_eligible?dkd_colors.lime+'26':dkd_colors.line}}><dkd.Row dkd_between><dkd_RN.View style={{flex:1}}><dkd.Text dkd_bold>{dkd_market.dkd_label}</dkd.Text><dkd.Text dkd_size={10} dkd_color={dkd_colors.muted}>{dkd_market.dkd_group||'Diğer'}</dkd.Text></dkd_RN.View><dkd.Text dkd_size={20} dkd_bold dkd_color={dkd_eligible?dkd_colors.lime:dkd_colors.text}>{dkd_decimal(dkd_market.dkd_odds)}</dkd.Text></dkd.Row>{dkd_eligible&&<dkd.Text dkd_size={10} dkd_color={dkd_colors.blue}>Normalize olasılık {dkd_percent(dkd_market.dkd_probability)}</dkd.Text>}</dkd.Card>})}</>}
  </dkd.Page>;
}

function dkd_Row({dkd_label,dkd_value,dkd_color}:{dkd_label:string;dkd_value:string;dkd_color:string}){return <dkd.Row dkd_between><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>{dkd_label}</dkd.Text><dkd.Text dkd_size={14} dkd_bold dkd_color={dkd_color}>{dkd_value}</dkd.Text></dkd.Row>;}
