import { dkd, dkd_colors } from '../src/dkd-ui';
export default function dkd_MethodScreen(){return <dkd.Page><dkd.Reveal><dkd.Badge dkd_color={dkd_colors.purple}>v0.6 ANALİZ MOTORU</dkd.Badge><dkd.Text dkd_size={29} dkd_bold dkd_style={{marginTop:10}}>Veri nereden geliyor?{'\n'}Nasıl hesaplanıyor?</dkd.Text></dkd.Reveal>{[
{dkd_title:'01 · Doğrudan kaynak taraması',dkd_color:dkd_colors.lime,dkd_body:'Herkese açık futbol bülteni ve bağımsız dbo_ collector’lar doğrulanabilir web verisini tarar. Spor/odds API’si kullanılmaz. CAPTCHA, bot koruması veya erişim engeli aşılmaz; kaynak engellerse sağlık durumu kaydedilir.'},
{dkd_title:'02 · Maç eşleştirme',dkd_color:dkd_colors.blue,dkd_body:'Takım adları normalize edilir; aynı başlangıç zamanına yakın karşılaşmalar isim benzerliğiyle eşleştirilir. Her sitenin ham maç kimliği ayrıca saklanır; kaynaklar birbirine karıştırılmaz.'},
{dkd_title:'03 · Oran ve market geçmişi',dkd_color:dkd_colors.purple,dkd_body:'Doğrulanan market oranları dbo_odds_history tablosuna zaman damgasıyla eklenir. Uygulama uydurma oran üretmez; matematiksel olarak tamamlanmamış market otomatik kupon olasılığına katılmaz.'},
{dkd_title:'04 · Marj normalizasyonu',dkd_color:dkd_colors.yellow,dkd_body:'Tamamlayıcı marketlerde her seçim için q = 1 / oran hesaplanır ve grup toplamına bölünerek bookmaker marjı temizlenir. 1X2, Alt/Üst, KG, İlk Yarı, Tek/Çift, Gol Aralığı ve tam dokuzlu İY/MS kendi doğru tamamlayıcı gruplarında normalize edilir.'},
{dkd_title:'05 · Risk profilleri',dkd_color:dkd_colors.coral,dkd_body:'Düşük Risk, Dengeli, Yüksek Getiri ve Ultra Getiri ayrı olasılık/oran bantları kullanır. Aşırı düşük olasılıklı dev oranlara ceza, tekrar eden market ailelerine çeşitlilik cezası uygulanır. Amaç yüksek getiri profilinin yalnızca 4-5 Gol veya 6+ Gol gibi uç seçimlere yığılmasını engellemektir.'},
{dkd_title:'06 · Genel kupon tahmini',dkd_color:dkd_colors.blue,dkd_body:'Raporun büyük yüzdesi, kupondaki her seçimin normalize tahmini gerçekleşme olasılığının aritmetik ortalamasıdır. Örneğin beş seçimin yüzdeleri toplanır ve 5’e bölünür. Bu metrik kupondaki seçimlerin ortalama güven düzeyini anlatır; beşinin aynı anda tutma olasılığı değildir.'},
{dkd_title:'07 · Birlikte gerçekleşme hesabı',dkd_color:dkd_colors.yellow,dkd_body:'Tüm seçimlerin aynı anda gerçekleşmesine ilişkin ayrı matematiksel değer seçim olasılıklarının çarpımıdır ve bağımsızlık varsayar. Bu nedenle maç sayısı arttıkça ortalama güven yüzdesinden çok daha hızlı küçülür. Rapor bu iki metriği artık ayrı etiketlerle gösterir.'},
{dkd_title:'08 · Getiri hesabı',dkd_color:dkd_colors.lime,dkd_body:'Toplam oran seçim oranlarının çarpımıdır. Olası brüt dönüş yalnızca tutar × toplam oran matematiksel senaryosudur. Genel seçim ortalaması veya birlikte gerçekleşme hesabı gerçek kazanç garantisi değildir.'},
{dkd_title:'09 · Snapshot ve izolasyon',dkd_color:dkd_colors.purple,dkd_body:'Rapor oluşturulduğu anda kullanılan maç/oran verisi cihazda snapshot olarak saklanır. Supabase tarafındaki bütün DraBornOdds nesneleri dbo_ öneki kullanır; aynı projedeki diğer uygulama verilerine dokunulmaz.'},
].map(dkd_item=><dkd.Card key={dkd_item.dkd_title}><dkd.Text dkd_size={18} dkd_bold dkd_color={dkd_item.dkd_color}>{dkd_item.dkd_title}</dkd.Text><dkd.Text dkd_size={14} dkd_color={dkd_colors.muted} dkd_selectable>{dkd_item.dkd_body}</dkd.Text></dkd.Card>)}<dkd.Notice dkd_text="DraBornOdds bilgi ve analiz aracıdır. Ortalama güven ve birlikte gerçekleşme değerleri farklı matematiksel metriklerdir; ikisi de kesinlik değildir. Uygulama bahis oynatmaz ve kazanç garantisi vermez."/></dkd.Page>;}
