import { dkd, dkd_colors } from '../src/dkd-ui';
export default function dkd_MethodScreen(){return <dkd.Page><dkd.Reveal><dkd.Badge dkd_color={dkd_colors.purple}>v0.7.4 ANALİZ MOTORU</dkd.Badge><dkd.Text dkd_size={29} dkd_bold dkd_style={{marginTop:10}}>Veri nereden geliyor?{'\n'}Nasıl hesaplanıyor?</dkd.Text></dkd.Reveal>{[
{dkd_title:'01 · Gerçek maç ve oran verisi',dkd_color:dkd_colors.lime,dkd_body:'DraBornOdds herkese açık futbol bültenlerini ve bağımsız dbo_ collector akışlarını tarar. Uygulama sahte maç veya uydurma oran üretmez. Kaynak erişilemezse eski doğrulanmış veri korunur ve durum ayrıca kaydedilir.'},
{dkd_title:'02 · Aynı maçın kaynaklarda eşleştirilmesi',dkd_color:dkd_colors.blue,dkd_body:'Takım isimleri ve başlama saatleri karşılaştırılır. Aynı karşılaşmaya ait oranlar tek maçta birleştirilir; farklı maçların verileri birbirine karıştırılmaz.'},
{dkd_title:'03 · Güncel oran geçmişi',dkd_color:dkd_colors.purple,dkd_body:'Doğrulanan oranlar zaman damgasıyla saklanır. Maç sonucu, Alt/Üst, Karşılıklı Gol, İlk Yarı ve diğer tamamlanmış marketler analizde kullanılabilir. Eksik veya matematiksel olarak tamamlanmamış market kupona sokulmaz.'},
{dkd_title:'04 · Oranlardan yaklaşık ihtimal çıkarma',dkd_color:dkd_colors.yellow,dkd_body:'Bir marketteki karşılıklı oranlar birlikte okunur ve bahis şirketinin payı matematiksel olarak çıkarılır. Böylece örneğin 1-X-2 için ev sahibi, beraberlik ve deplasman adına daha anlaşılır yaklaşık ihtimaller elde edilir.'},
{dkd_title:'05 · Takım formu ve maç geçmişi',dkd_color:dkd_colors.coral,dkd_body:'Kaynakta doğrulanabiliyorsa takımların son maç skorları, galibiyet-beraberlik-mağlubiyet serisi, lig sırası ve iki takımın yakın geçmişteki doğrudan karşılaşmaları seçim açıklamasına eklenir. Verisi olmayan bilgi uydurulmaz.'},
{dkd_title:'06 · Kırmızı kart, ceza ve eksik oyuncu',dkd_color:dkd_colors.blue,dkd_body:'Kırmızı kart, cezalı veya eksik oyuncu bilgisi yalnızca doğrulanmış veri akışında varsa seçim sebebine katılır. Böyle bir veri yoksa uygulama “varmış gibi” yorum yapmaz. Aynı kural dinlenme süresi ve kadro eksikleri için de geçerlidir.'},
{dkd_title:'07 · Risk profilleri',dkd_color:dkd_colors.coral,dkd_body:'Düşük Risk, Dengeli, Yüksek Getiri ve Ultra Getiri farklı oran ve ihtimal aralıklarını tercih eder. Çok uç oranlara ceza uygulanır; aynı tür seçimlerin kupona gereksiz şekilde yığılması engellenir.'},
{dkd_title:'08 · Neden bu seçim?',dkd_color:dkd_colors.lime,dkd_body:'Açıklama artık teknik terimlerle değil; son maç skorları, form, lig sırası, önceki karşılaşmalar ve güncel oranların ne söylediği üzerinden sade Türkçeyle yazılır. Örneğin “son 5 maçta 3 galibiyet”, “ligde 4. sırada” veya “iki takımın son maçları 2-1 ve 1-0 bitti” gibi somut gerekçeler gösterilir.'},
{dkd_title:'09 · Kupon tahmini ve getiri hesabı',dkd_color:dkd_colors.yellow,dkd_body:'Kupondaki seçimlerin ortalama ihtimali ayrı, tüm seçimlerin birlikte gerçekleşmesine ilişkin matematiksel hesap ayrı gösterilir. Toplam oran ve olası brüt dönüş yalnızca senaryodur; sonuç veya kazanç garantisi değildir.'},
{dkd_title:'10 · Snapshot ve veri izolasyonu',dkd_color:dkd_colors.purple,dkd_body:'Rapor oluşturulduğu anda kullanılan maç ve oran verisi snapshot olarak saklanır. Supabase tarafındaki DraBornOdds nesneleri dbo_ önekiyle tutulur ve aynı projedeki diğer uygulama verilerinden ayrılır.'},
].map(dkd_item=><dkd.Card key={dkd_item.dkd_title}><dkd.Text dkd_size={18} dkd_bold dkd_color={dkd_item.dkd_color}>{dkd_item.dkd_title}</dkd.Text><dkd.Text dkd_size={14} dkd_color={dkd_colors.muted} dkd_selectable>{dkd_item.dkd_body}</dkd.Text></dkd.Card>)}<dkd.Notice dkd_text="DraBornOdds bilgi ve analiz aracıdır. Son maçlar, sıralama, kadro ve oran verileri yalnızca doğrulanabildiği ölçüde kullanılır; hiçbir analiz kesin sonuç veya kazanç garantisi değildir."/></dkd.Page>;}
