import * as dkd_RN from 'react-native';
import * as dkd_Router from 'expo-router';
import { dkd, dkd_colors } from '../../src/dkd-ui';
import { dkd_decimal, dkd_money, dkd_percent, dkd_reason, dkd_risks, dkd_shareText, dkd_summarize } from '../../src/dkd-engine';
import { dkd_useStore } from '../../src/dkd-store';

export default function dkd_ReportScreen(){
  const {dkd_id}=dkd_Router.useLocalSearchParams<{dkd_id:string}>();const dkd_store=dkd_useStore();const dkd_saved=dkd_store.dkd_stored.dkd_coupons.find(dkd_item=>dkd_item.dkd_id===dkd_id);const dkd_coupon=dkd_saved??dkd_store.dkd_reports.find(dkd_item=>dkd_item.dkd_id===dkd_id);
  if(!dkd_coupon)return <dkd.Page><dkd.Empty dkd_title="Rapor bulunamadı" dkd_body="Kaydedilmemiş raporlar uygulama yeniden açıldığında temizlenir." dkd_action="Analiz atölyesine dön" dkd_onPress={()=>dkd_Router.router.replace('/builder')}/></dkd.Page>;
  const dkd_summary=dkd_summarize(dkd_coupon.dkd_picks,dkd_coupon.dkd_snapshot,dkd_coupon.dkd_stake),dkd_risk=dkd_risks[dkd_coupon.dkd_risk];const dkd_share=async()=>{try{await dkd_RN.Share.share({message:dkd_shareText(dkd_coupon,dkd_coupon.dkd_snapshot),title:'DraBornOdds analiz raporu'});}catch{dkd_store.dkd_notify('Paylaşım açılamadı. Raporunu cihaza kaydedebilirsin.');}};
  return <dkd.Page><dkd.Reveal><dkd.Row dkd_between><dkd.Badge dkd_color={dkd_risk.dkd_color} dkd_icon={dkd_coupon.dkd_mode==='auto'?dkd_risk.dkd_icon:'ticket'}>{dkd_coupon.dkd_mode==='auto'?dkd_risk.dkd_name.toLocaleUpperCase('tr-TR'):'KENDİ SEÇİMLERİN'}</dkd.Badge><dkd.Badge dkd_color={dkd_colors.lime}>SNAPSHOT</dkd.Badge></dkd.Row><dkd.Text dkd_size={29} dkd_bold dkd_style={{marginTop:12}}>Analiz raporun hazır.</dkd.Text><dkd.Text dkd_size={13} dkd_color={dkd_colors.muted}>{dkd_coupon.dkd_picks.length} maç · {new Date(dkd_coupon.dkd_createdAt).toLocaleString('tr-TR')}</dkd.Text></dkd.Reveal>
    <dkd.Card dkd_style={{borderColor:dkd_risk.dkd_color+'70'}}><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>TAHMİNİ GERÇEKLEŞME OLASILIĞI</dkd.Text><dkd.Text dkd_size={36} dkd_bold dkd_color={dkd_risk.dkd_color}>{dkd_percent(dkd_summary.dkd_probability)}</dkd.Text><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>Piyasa oranlarından marj temizlenerek hesaplanan birleşik tahmin · duyarlılık {dkd_percent(dkd_summary.dkd_lower)} – {dkd_percent(dkd_summary.dkd_upper)}</dkd.Text><dkd.Row dkd_between><dkd_RN.View><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>Toplam oran</dkd.Text><dkd.Text dkd_size={25} dkd_bold>{dkd_decimal(dkd_summary.dkd_odds)}</dkd.Text></dkd_RN.View><dkd_RN.View><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>Tutar senaryosu</dkd.Text><dkd.Text dkd_size={25} dkd_bold>{dkd_money(dkd_coupon.dkd_stake)}</dkd.Text></dkd_RN.View></dkd.Row><dkd_RN.View style={{backgroundColor:dkd_colors.lime+'12',borderRadius:16,padding:16,gap:4}}><dkd.Text dkd_size={12} dkd_color={dkd_colors.lime}>OLASI BRÜT DÖNÜŞ</dkd.Text><dkd.Text dkd_size={31} dkd_bold dkd_color={dkd_colors.lime}>{dkd_money(dkd_summary.dkd_gross)}</dkd.Text><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>Matematiksel senaryo; kazanç garantisi değildir.</dkd.Text></dkd_RN.View></dkd.Card>
    <dkd.Section dkd_title="Seçimlerin gerekçesi" dkd_subtitle="Rapor anındaki oran ve normalize piyasa olasılıkları."/>
    {dkd_summary.dkd_rows.map((dkd_row,dkd_index)=><dkd.Card key={dkd_row.dkd_match.dkd_id}><dkd.Row dkd_between><dkd.Badge dkd_color={dkd_row.dkd_match.dkd_color}>0{dkd_index+1} · {dkd_row.dkd_match.dkd_league}</dkd.Badge><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>{dkd_row.dkd_match.dkd_time}</dkd.Text></dkd.Row><dkd.Text dkd_bold dkd_size={17}>{dkd_row.dkd_match.dkd_home.dkd_name} – {dkd_row.dkd_match.dkd_away.dkd_name}</dkd.Text><dkd.Row dkd_between><dkd.Badge>{dkd_row.dkd_market.dkd_label}</dkd.Badge><dkd.Text dkd_size={22} dkd_bold>{dkd_decimal(dkd_row.dkd_market.dkd_odds)}</dkd.Text></dkd.Row><dkd.Row dkd_between><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>Tahmini gerçekleşme</dkd.Text><dkd.Text dkd_bold dkd_color={dkd_colors.lime}>{dkd_percent(dkd_row.dkd_market.dkd_probability)}</dkd.Text></dkd.Row><dkd.Text dkd_size={13} dkd_color={dkd_colors.muted}>{dkd_reason(dkd_row.dkd_match,dkd_row.dkd_market)}</dkd.Text><dkd.Button dkd_label="Maç analizini aç" dkd_variant="secondary" dkd_small dkd_icon="arrow" dkd_onPress={()=>dkd_Router.router.push(`/match/${dkd_row.dkd_match.dkd_id}`)}/></dkd.Card>)}
    <dkd.Card dkd_style={{borderColor:'#54422E'}}><dkd.Text dkd_bold dkd_color={dkd_colors.yellow}>Belirsizlik görünür kalır.</dkd.Text><dkd.Text dkd_size={13} dkd_color={dkd_colors.muted}>Her seçimin normalize olasılığı ±7 puan değiştiğinde birleşik değer {dkd_percent(dkd_summary.dkd_lower)} – {dkd_percent(dkd_summary.dkd_upper)} aralığına gelir. Bu bir duyarlılık senaryosudur, güven aralığı değildir.</dkd.Text><dkd.Button dkd_label="Hesaplama yöntemini incele" dkd_variant="ghost" dkd_small dkd_onPress={()=>dkd_Router.router.push('/method')}/></dkd.Card>
    <dkd.Button dkd_label={dkd_saved?'Rapor cihazında kayıtlı':'Raporu cihazıma kaydet'} dkd_icon={dkd_saved?'check':'bookmark'} dkd_disabled={!!dkd_saved} dkd_onPress={()=>dkd_store.dkd_saveReport(dkd_coupon)}/><dkd.Row><dkd.Button dkd_label="Raporu paylaş" dkd_variant="secondary" dkd_icon="share" dkd_style={{flex:1}} dkd_onPress={dkd_share}/><dkd.Button dkd_label="Yeni analiz" dkd_variant="secondary" dkd_icon="plus" dkd_style={{flex:1}} dkd_onPress={()=>dkd_Router.router.navigate('/builder')}/></dkd.Row><dkd.Notice dkd_text="DraBornOdds olasılık ve oran analizi sunar; bahis oynatmaz. Olasılık kesinlik değildir."/>
  </dkd.Page>;
}
