import * as dkd_RN from 'react-native';
import * as dkd_Router from 'expo-router';
import { dkd, dkd_colors } from '../../src/dkd-ui';
import { dkd_matches, dkd_fixtureDay } from '../../src/dkd-data';
import { dkd_decimal, dkd_money, dkd_percent, dkd_reason, dkd_risks, dkd_shareText, dkd_summarize } from '../../src/dkd-engine';
import { dkd_useStore } from '../../src/dkd-store';

export default function dkd_ReportScreen(){
  const {dkd_id}=dkd_Router.useLocalSearchParams<{dkd_id:string}>();
  const dkd_store=dkd_useStore();
  const dkd_saved=dkd_store.dkd_stored.dkd_coupons.find(dkd_item=>dkd_item.dkd_id===dkd_id);
  const dkd_coupon=dkd_saved ?? dkd_store.dkd_reports.find(dkd_item=>dkd_item.dkd_id===dkd_id);
  if(!dkd_coupon)return <dkd.Page><dkd.Empty dkd_title="Rapor bulunamadı" dkd_body="Kaydedilmemiş raporlar uygulama yeniden açıldığında temizlenir. Yeni bir senaryo oluşturabilirsin." dkd_action="Kupon atölyesine dön" dkd_onPress={()=>dkd_Router.router.replace('/builder')}/></dkd.Page>;
  const dkd_summary=dkd_summarize(dkd_coupon.dkd_picks,dkd_matches,dkd_coupon.dkd_stake);
  const dkd_risk=dkd_risks[dkd_coupon.dkd_risk];
  const dkd_share=async()=>{try{await dkd_RN.Share.share({message:dkd_shareText(dkd_coupon,dkd_matches),title:'DraBornOdds demo kupon raporu'});}catch{dkd_store.dkd_notify('Paylaşım açılamadı. Raporunu cihaza kaydedebilirsin.');}};
  return <dkd.Page><dkd.Reveal><dkd.Row dkd_between><dkd.Badge dkd_color={dkd_risk.dkd_color} dkd_icon={dkd_coupon.dkd_mode==='auto'?dkd_risk.dkd_icon:'ticket'}>{dkd_coupon.dkd_mode==='auto'?dkd_risk.dkd_name.toLocaleUpperCase('tr-TR'):'KENDİ SEÇİMLERİN'}</dkd.Badge><dkd.Badge dkd_color={dkd_colors.muted}>DEMO RAPOR</dkd.Badge></dkd.Row><dkd.Text dkd_size={29} dkd_bold dkd_style={{marginTop:12}}>Oyun planın hazır.</dkd.Text><dkd.Text dkd_size={13} dkd_color={dkd_colors.muted}>{dkd_coupon.dkd_picks.length} maç · {new Date(dkd_coupon.dkd_createdAt).toLocaleDateString('tr-TR')} · TSİ</dkd.Text></dkd.Reveal>
    <dkd.Reveal dkd_delay={80}><dkd.Card dkd_style={{borderColor:dkd_risk.dkd_color+'70',gap:20}}><dkd.Row><dkd_RN.View style={{flex:1,gap:5}}><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>ÖRNEK BİRLEŞİK OLASILIK</dkd.Text><dkd.Text dkd_size={36} dkd_bold dkd_color={dkd_risk.dkd_color} dkd_selectable>{dkd_percent(dkd_summary.dkd_probability)}</dkd.Text><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>Tüm seçimlerin birlikte gerçekleşmesi</dkd.Text></dkd_RN.View><dkd.Ring dkd_value={dkd_summary.dkd_probability} dkd_color={dkd_risk.dkd_color} dkd_size={100}/></dkd.Row><dkd_RN.View style={{height:1,backgroundColor:dkd_colors.line}}/><dkd.Row dkd_between><dkd_RN.View style={{flex:1,gap:3}}><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>Toplam oran</dkd.Text><dkd.Text dkd_size={25} dkd_bold dkd_selectable>{dkd_decimal(dkd_summary.dkd_odds)}</dkd.Text></dkd_RN.View><dkd_RN.View style={{flex:1,gap:3}}><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>Senaryo tutarı</dkd.Text><dkd.Text dkd_size={25} dkd_bold dkd_selectable>{dkd_money(dkd_coupon.dkd_stake)}</dkd.Text></dkd_RN.View></dkd.Row><dkd_RN.View style={{backgroundColor:dkd_colors.lime+'12',borderRadius:16,padding:16,gap:4}}><dkd.Text dkd_size={12} dkd_color={dkd_colors.lime}>OLASI BRÜT DÖNÜŞ</dkd.Text><dkd.Text dkd_size={31} dkd_bold dkd_color={dkd_colors.lime} dkd_selectable>{dkd_money(dkd_summary.dkd_gross)}</dkd.Text><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>Tüm seçimler gerçekleşirse · Tutar dahil</dkd.Text><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>Olası net fark: {dkd_money(dkd_summary.dkd_net)}</dkd.Text></dkd_RN.View><dkd.Text dkd_size={12} dkd_color={dkd_colors.coral}>En az bir seçimin gerçekleşmeme olasılığı: {dkd_percent(1-dkd_summary.dkd_probability)}</dkd.Text></dkd.Card></dkd.Reveal>
    <dkd.Section dkd_title="Bu seçimler neden burada?" dkd_subtitle="Her karşılaşmanın gerekçesini incele."/>
    {dkd_summary.dkd_rows.map((dkd_row,dkd_index)=><dkd.Card key={dkd_row.dkd_match.dkd_id}><dkd.Row dkd_between><dkd.Badge dkd_color={dkd_row.dkd_match.dkd_color}>0{dkd_index+1} · {dkd_row.dkd_match.dkd_league}</dkd.Badge><dkd.Text dkd_size={13} dkd_color={dkd_colors.muted}>{dkd_row.dkd_match.dkd_time}</dkd.Text></dkd.Row><dkd.Text dkd_bold dkd_size={17}>{dkd_row.dkd_match.dkd_home.dkd_name}{'\n'}{dkd_row.dkd_match.dkd_away.dkd_name}</dkd.Text><dkd.Row dkd_between><dkd.Badge>{dkd_row.dkd_market.dkd_label}</dkd.Badge><dkd.Text dkd_size={22} dkd_bold>{dkd_decimal(dkd_row.dkd_market.dkd_odds)}</dkd.Text></dkd.Row><dkd.Row dkd_between><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>Örnek model olasılığı</dkd.Text><dkd.Text dkd_bold dkd_color={dkd_colors.lime}>{dkd_percent(dkd_row.dkd_market.dkd_probability)}</dkd.Text></dkd.Row><dkd.Text dkd_size={13} dkd_color={dkd_colors.muted}>{dkd_reason(dkd_row.dkd_match,dkd_row.dkd_market)}</dkd.Text><dkd.Button dkd_label="Maçın detaylı analizi" dkd_variant="secondary" dkd_small dkd_icon="arrow" dkd_onPress={()=>dkd_Router.router.push(`/match/${dkd_row.dkd_match.dkd_id}`)}/></dkd.Card>)}
    <dkd.Card dkd_style={{borderColor:'#54422E'}}><dkd.Row><dkd.Icon dkd_name="shield" dkd_color={dkd_colors.yellow}/><dkd.Text dkd_bold>Belirsizliği de gör.</dkd.Text></dkd.Row><dkd.Text dkd_size={13} dkd_color={dkd_colors.muted}>Her seçimin olasılığını ±7 yüzde puan değiştirdiğimizde birleşik olasılık {dkd_percent(dkd_summary.dkd_lower)} – {dkd_percent(dkd_summary.dkd_upper)} aralığına geliyor.</dkd.Text><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>Bu bir duyarlılık örneğidir; istatistiksel güven aralığı değildir. Birleşik hesap, maçların bağımsız olduğunu varsayar. Aynı takımların farklı maçları bu varsayımı zayıflatabilir.</dkd.Text><dkd.Button dkd_label="Hesaplama yöntemini incele" dkd_variant="ghost" dkd_small dkd_onPress={()=>dkd_Router.router.push('/method')}/></dkd.Card>
    {dkd_coupon.dkd_fixtureDay!==dkd_fixtureDay&&<dkd.Notice dkd_text="Bu rapor önceki bir demo gününde oluşturuldu. Kayıtlı oranlar aynı örnek veri setine aittir; maç ekranındaki göreli tarihler bugüne göre gösterilir."/>}
    <dkd.Button dkd_label={dkd_saved?'Rapor cihazında kayıtlı':'Raporu cihazıma kaydet'} dkd_icon={dkd_saved?'check':'bookmark'} dkd_disabled={!!dkd_saved} dkd_onPress={()=>dkd_store.dkd_saveReport(dkd_coupon)}/>
    <dkd.Row><dkd.Button dkd_label="Raporu paylaş" dkd_variant="secondary" dkd_icon="share" dkd_style={{flex:1}} dkd_onPress={dkd_share}/><dkd.Button dkd_label="Yeni kupon" dkd_variant="secondary" dkd_icon="plus" dkd_style={{flex:1}} dkd_onPress={()=>dkd_Router.router.navigate('/builder')}/></dkd.Row><dkd.Notice/>
  </dkd.Page>;
}
