import * as dkd_RN from 'react-native';
import * as dkd_Router from 'expo-router';
import { dkd, dkd_colors } from '../../src/dkd-ui';
import { dkd_LiveMatchCard } from '../../src/dkd-live-card';
import { dkd_useStore } from '../../src/dkd-store';
import { dkd_risks } from '../../src/dkd-engine';
import type { dkd_Risk } from '../../src/dkd-types';

const dkd_liveCard={MatchCard:dkd_LiveMatchCard};

export default function dkd_HomeScreen(){
  const dkd_store=dkd_useStore();
  const dkd_matches=dkd_store.dkd_matches;
  const dkd_leagues=new Set(dkd_matches.map(dkd_match=>dkd_match.dkd_league)).size;
  const dkd_oddsReady=dkd_matches.filter(dkd_match=>dkd_match.dkd_markets.length>=3).length;
  const dkd_fixtureReady=dkd_matches.length>0;
  return <dkd.Page>
    <dkd.Reveal><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted} dkd_bold dkd_style={{letterSpacing:1.4}}>CANLI VERİ MERKEZİ</dkd.Text><dkd.Text dkd_size={32} dkd_bold dkd_style={{marginTop:10,lineHeight:39}}>Oyunu gör.{'\n'}<dkd_RN.Text style={{color:dkd_colors.lime}}>Veriyi konuştur.</dkd_RN.Text></dkd.Text><dkd.Text dkd_size={14} dkd_color={dkd_colors.muted} dkd_style={{marginTop:9}}>Güncel gerçek fikstür yüklenir. Doğrulanmış 1X2 oranı geldiğinde analiz ve kupon seçimleri otomatik açılır.</dkd.Text></dkd.Reveal>
    <dkd.Row dkd_gap={9}>{[{v:String(dkd_matches.length),l:'Fikstür',c:dkd_colors.blue,i:'ball'},{v:String(dkd_oddsReady),l:'1X2 hazır',c:dkd_colors.lime,i:'chart'},{v:String(dkd_leagues),l:'Lig',c:dkd_colors.purple,i:'trophy'}].map(dkd_item=><dkd.Card key={dkd_item.l} dkd_style={{flex:1,padding:12,gap:5,borderRadius:16}}><dkd.Icon dkd_name={dkd_item.i} dkd_size={18} dkd_color={dkd_item.c}/><dkd.Text dkd_size={24} dkd_bold>{dkd_item.v}</dkd.Text><dkd.Text dkd_size={10} dkd_color={dkd_colors.muted}>{dkd_item.l}</dkd.Text></dkd.Card>)}</dkd.Row>
    {dkd_store.dkd_liveState==='error'?<dkd.Empty dkd_title="Canlı veri alınamadı" dkd_body={dkd_store.dkd_liveError||'Bağlantıyı kontrol edip yeniden deneyebilirsin.'} dkd_icon="refresh" dkd_action="Yeniden dene" dkd_onPress={()=>dkd_store.dkd_refreshLive()}/>:!dkd_matches.length?<dkd.Empty dkd_title="Güncel fikstür yükleniyor" dkd_body="Fikstür ve 1X2 kaynakları yenileniyor. Doğrulanmamış maç veya sahte oran gösterilmez." dkd_icon="clock" dkd_action="Veriyi yenile" dkd_onPress={()=>dkd_store.dkd_refreshLive()}/>:<><dkd.Section dkd_title={dkd_oddsReady?'Günün odağı':'Güncel fikstür'} dkd_subtitle={dkd_oddsReady?'Doğrulanmış 1X2 kalitesine göre güncel karşılaşmalar.':'Güncel karşılaşmalar hazır; 1X2 oran hattı ayrıca doğrulanıyor.'} dkd_action="Tüm maçlar" dkd_onPress={()=>dkd_Router.router.push('/matches')}/>{dkd_matches.slice(0,3).map((dkd_match,dkd_i)=><dkd_liveCard.MatchCard key={dkd_match.dkd_id} dkd_match={dkd_match} dkd_featured={dkd_i===0}/>)}</>}
    <dkd.Section dkd_title="Ritmini seç" dkd_subtitle={dkd_oddsReady?'Profil yalnızca analiz sıralamasını değiştirir; kesinlik ifade etmez.':'Analiz profilleri doğrulanmış 1X2 oranı bulunan maçlarda çalışır.'}/><dkd_RN.View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}>{(Object.keys(dkd_risks) as dkd_Risk[]).map(dkd_key=>{const dkd_risk=dkd_risks[dkd_key];return <dkd_RN.Pressable key={dkd_key} accessibilityRole="button" accessibilityLabel={`${dkd_risk.dkd_name} analiz`} onPress={()=>dkd_Router.router.push({pathname:'/builder',params:{dkd_profile:dkd_key}})} style={{width:'48%',flexGrow:1,backgroundColor:dkd_colors.card,borderWidth:1,borderColor:dkd_colors.line,borderRadius:19,padding:16,gap:10}}><dkd.Icon dkd_name={dkd_risk.dkd_icon} dkd_color={dkd_risk.dkd_color}/><dkd.Text dkd_bold dkd_color={dkd_risk.dkd_color}>{dkd_risk.dkd_name}</dkd.Text><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_risk.dkd_subtitle}</dkd.Text></dkd_RN.Pressable>;})}</dkd_RN.View>
    <dkd.Section dkd_title="Veri durumu" dkd_subtitle="Fikstür ve oran akışları birbirinden bağımsız kontrol edilir."/>
    <dkd.Card dkd_style={{padding:14,borderRadius:16}}><dkd.Row dkd_between><dkd.Row><dkd.Icon dkd_name="calendar" dkd_size={18} dkd_color={dkd_colors.blue}/><dkd.Text dkd_bold>Fikstür akışı</dkd.Text></dkd.Row><dkd.Badge dkd_color={dkd_fixtureReady?dkd_colors.lime:dkd_colors.yellow}>{dkd_fixtureReady?'GÜNCEL':'YENİLENİYOR'}</dkd.Badge></dkd.Row><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_fixtureReady?`${dkd_matches.length} gerçek karşılaşma yüklendi.`:'Güncel karşılaşmalar kontrol ediliyor.'}</dkd.Text></dkd.Card>
    <dkd.Card dkd_style={{padding:14,borderRadius:16}}><dkd.Row dkd_between><dkd.Row><dkd.Icon dkd_name="chart" dkd_size={18} dkd_color={dkd_colors.lime}/><dkd.Text dkd_bold>1X2 oran akışı</dkd.Text></dkd.Row><dkd.Badge dkd_color={dkd_oddsReady?dkd_colors.lime:dkd_colors.yellow}>{dkd_oddsReady?'HAZIR':'BEKLENİYOR'}</dkd.Badge></dkd.Row><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_oddsReady?`${dkd_oddsReady} karşılaşmada doğrulanmış 1X2 oranı hazır.`:'Kaynaklardan doğrulanabilir 1X2 oranı geldiğinde analiz otomatik açılacak.'}</dkd.Text></dkd.Card>
    <dkd.Button dkd_label="Canlı veriyi yenile" dkd_icon="refresh" dkd_variant="secondary" dkd_onPress={()=>dkd_store.dkd_refreshLive()}/><dkd.Notice dkd_text="Doğrulanmamış oran tahmin edilmez. Bir karşılaşmanın oranı hazır değilse fikstür yine gösterilir fakat kupona eklenemez."/><dkd.Text dkd_size={10} dkd_color={dkd_colors.muted} dkd_style={{textAlign:'center'}}>DraBornEagle ekosistemi · DKD_draborneagle_v0.2</dkd.Text>
  </dkd.Page>;
}
