import * as dkd_RN from 'react-native';
import * as dkd_Router from 'expo-router';
import { dkd, dkd_colors } from '../../src/dkd-ui';
import { dkd_useStore } from '../../src/dkd-store';
import { dkd_risks } from '../../src/dkd-engine';
import type { dkd_Risk } from '../../src/dkd-types';

export default function dkd_HomeScreen(){
  const dkd_store=dkd_useStore();const dkd_matches=dkd_store.dkd_matches;const dkd_leagues=new Set(dkd_matches.map(dkd_match=>dkd_match.dkd_league)).size;const dkd_healthy=dkd_store.dkd_sources.filter(dkd_source=>dkd_source.dkd_status==='ok').length;
  return <dkd.Page>
    <dkd.Reveal><dkd.Row dkd_between><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted} dkd_bold dkd_style={{letterSpacing:1.4}}>CANLI VERİ MERKEZİ</dkd.Text><dkd.Badge dkd_color={dkd_store.dkd_liveState==='ready'?dkd_colors.lime:dkd_colors.yellow}>{dkd_store.dkd_liveState==='loading'?'YÜKLENİYOR':dkd_store.dkd_liveState==='error'?'BAĞLANTI HATASI':'SUPABASE'}</dkd.Badge></dkd.Row><dkd.Text dkd_size={32} dkd_bold dkd_style={{marginTop:10,lineHeight:39}}>Oyunu gör.{'\n'}<dkd_RN.Text style={{color:dkd_colors.lime}}>Veriyi konuştur.</dkd_RN.Text></dkd.Text><dkd.Text dkd_size={14} dkd_color={dkd_colors.muted} dkd_style={{marginTop:9}}>Kaynaklardan doğrulanabilen güncel 1X2 verileri Supabase üzerinde birleştirilir. Veri yoksa örnek maç gösterilmez.</dkd.Text></dkd.Reveal>
    <dkd.Row dkd_gap={9}>{[{v:String(dkd_matches.length),l:'Canlı maç',c:dkd_colors.blue,i:'ball'},{v:String(dkd_leagues),l:'Lig',c:dkd_colors.purple,i:'trophy'},{v:`${dkd_healthy}/${dkd_store.dkd_sources.length}`,l:'Aktif kaynak',c:dkd_colors.lime,i:'refresh'}].map(dkd_item=><dkd.Card key={dkd_item.l} dkd_style={{flex:1,padding:12,gap:5,borderRadius:16}}><dkd.Icon dkd_name={dkd_item.i} dkd_size={18} dkd_color={dkd_item.c}/><dkd.Text dkd_size={24} dkd_bold>{dkd_item.v}</dkd.Text><dkd.Text dkd_size={10} dkd_color={dkd_colors.muted}>{dkd_item.l}</dkd.Text></dkd.Card>)}</dkd.Row>
    {dkd_store.dkd_liveState==='error'?<dkd.Empty dkd_title="Canlı veri alınamadı" dkd_body={dkd_store.dkd_liveError||'Bağlantıyı kontrol edip yeniden deneyebilirsin.'} dkd_icon="refresh" dkd_action="Yeniden dene" dkd_onPress={()=>dkd_store.dkd_refreshLive()}/>:!dkd_matches.length?<dkd.Empty dkd_title="Doğrulanmış maç bekleniyor" dkd_body="Collector’lar çalışıyor. Kaynaklardan üç 1X2 oranı birlikte doğrulanmadan uygulama maç üretmez." dkd_icon="clock" dkd_action="Veriyi yenile" dkd_onPress={()=>dkd_store.dkd_refreshLive()}/>:<><dkd.Section dkd_title="Günün odağı" dkd_subtitle="Kaynak birleştirme kalitesine göre güncel karşılaşmalar." dkd_action="Tüm maçlar" dkd_onPress={()=>dkd_Router.router.push('/matches')}/>{dkd_matches.slice(0,2).map((dkd_match,dkd_i)=><dkd.MatchCard key={dkd_match.dkd_id} dkd_match={dkd_match} dkd_featured={dkd_i===0}/>)}</>}
    <dkd.Section dkd_title="Ritmini seç" dkd_subtitle="Profil yalnızca analiz sıralamasını değiştirir; kesinlik ifade etmez."/><dkd_RN.View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}>{(Object.keys(dkd_risks) as dkd_Risk[]).map(dkd_key=>{const dkd_risk=dkd_risks[dkd_key];return <dkd_RN.Pressable key={dkd_key} accessibilityRole="button" accessibilityLabel={`${dkd_risk.dkd_name} analiz`} onPress={()=>dkd_Router.router.push({pathname:'/builder',params:{dkd_profile:dkd_key}})} style={{width:'48%',flexGrow:1,backgroundColor:dkd_colors.card,borderWidth:1,borderColor:dkd_colors.line,borderRadius:19,padding:16,gap:10}}><dkd.Icon dkd_name={dkd_risk.dkd_icon} dkd_color={dkd_risk.dkd_color}/><dkd.Text dkd_bold dkd_color={dkd_risk.dkd_color}>{dkd_risk.dkd_name}</dkd.Text><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_risk.dkd_subtitle}</dkd.Text></dkd_RN.Pressable>;})}</dkd_RN.View>
    <dkd.Section dkd_title="Kaynak sağlığı" dkd_subtitle="Koruma sayfası görülürse aşılmaz; durum açıkça raporlanır."/>{dkd_store.dkd_sources.map(dkd_source=><dkd.Card key={dkd_source.dkd_id} dkd_style={{padding:14,borderRadius:16}}><dkd.Row dkd_between><dkd.Text dkd_bold>{dkd_source.dkd_name}</dkd.Text><dkd.Badge dkd_color={dkd_source.dkd_status==='ok'?dkd_colors.lime:dkd_source.dkd_status==='blocked'?dkd_colors.coral:dkd_colors.yellow}>{dkd_source.dkd_status.toLocaleUpperCase('tr-TR')}</dkd.Badge></dkd.Row><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_source.dkd_matchCount} doğrulanmış maç{dkd_source.dkd_lastError?` · ${dkd_source.dkd_lastError}`:''}</dkd.Text></dkd.Card>)}
    <dkd.Button dkd_label="Canlı veriyi yenile" dkd_icon="refresh" dkd_variant="secondary" dkd_onPress={()=>dkd_store.dkd_refreshLive()}/><dkd.Notice dkd_text="Olasılıklar kaynaklardaki 1X2 oranlarının marj-normalize piyasa değerleridir. Sonuç garantisi değildir; DraBornOdds bahis işlemi gerçekleştirmez."/><dkd.Text dkd_size={10} dkd_color={dkd_colors.muted} dkd_style={{textAlign:'center'}}>DraBornEagle ekosistemi · DKD_draborneagle_v0.2</dkd.Text>
  </dkd.Page>;
}
