import * as dkd_RN from 'react-native';
import * as dkd_Router from 'expo-router';
import { dkd, dkd_colors } from '../../src/dkd-ui';
import { dkd_LiveMatchCard } from '../../src/dkd-live-card';
import { dkd_useStore } from '../../src/dkd-store';
import { dkd_risks } from '../../src/dkd-engine';
import type { dkd_Risk } from '../../src/dkd-types';

const dkd_liveCard={MatchCard:dkd_LiveMatchCard};
export default function dkd_HomeScreen(){
  const dkd_store=dkd_useStore(),dkd_matches=dkd_store.dkd_matches,dkd_leagues=new Set(dkd_matches.map(dkd_match=>dkd_match.dkd_league)).size,dkd_oddsReady=dkd_matches.filter(dkd_match=>dkd_match.dkd_markets.length>=3).length,dkd_marketCount=dkd_matches.reduce((dkd_sum,dkd_match)=>dkd_sum+dkd_match.dkd_markets.length,0),dkd_fixtureReady=dkd_matches.length>0,dkd_focus=[...dkd_matches].sort((dkd_a,dkd_b)=>(dkd_b.dkd_markets.length>0?1:0)-(dkd_a.dkd_markets.length>0?1:0)||dkd_b.dkd_quality-dkd_a.dkd_quality||new Date(dkd_a.dkd_startAt).getTime()-new Date(dkd_b.dkd_startAt).getTime());
  return <dkd.Page>
    <dkd.Reveal><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted} dkd_bold dkd_style={{letterSpacing:1.4}}>CANLI VERİ MERKEZİ</dkd.Text><dkd.Text dkd_size={32} dkd_bold dkd_style={{marginTop:10,lineHeight:39}}>Oyunu gör.{'\n'}<dkd_RN.Text style={{color:dkd_colors.lime}}>Veriyi konuştur.</dkd_RN.Text></dkd.Text><dkd.Text dkd_size={14} dkd_color={dkd_colors.muted} dkd_style={{marginTop:9}}>Güncel futbol bülteni ve doğrulanmış market oranları taranır. Analiz motoru mevcut marketleri birlikte değerlendirerek risk profiline uygun seçimleri sıralar.</dkd.Text></dkd.Reveal>
    <dkd.Row dkd_gap={9}>{[{v:String(dkd_matches.length),l:'Maç',c:dkd_colors.blue,i:'ball'},{v:String(dkd_oddsReady),l:'Oranlı maç',c:dkd_colors.lime,i:'chart'},{v:String(dkd_marketCount),l:'Market oranı',c:dkd_colors.purple,i:'trophy'}].map(dkd_item=><dkd.Card key={dkd_item.l} dkd_style={{flex:1,padding:12,gap:5,borderRadius:16}}><dkd.Icon dkd_name={dkd_item.i} dkd_size={18} dkd_color={dkd_item.c}/><dkd.Text dkd_size={24} dkd_bold>{dkd_item.v}</dkd.Text><dkd.Text dkd_size={10} dkd_color={dkd_colors.muted}>{dkd_item.l}</dkd.Text></dkd.Card>)}</dkd.Row>
    {dkd_store.dkd_liveState==='error'?<dkd.Empty dkd_title="Canlı veri alınamadı" dkd_body={dkd_store.dkd_liveError||'Bağlantıyı kontrol edip yeniden deneyebilirsin.'} dkd_icon="refresh" dkd_action="Yeniden dene" dkd_onPress={()=>dkd_store.dkd_refreshLive()}/>:!dkd_matches.length?<dkd.Empty dkd_title="Güncel bülten yükleniyor" dkd_body="Fikstür ve oran kaynakları yenileniyor. Doğrulanmamış maç veya sahte oran gösterilmez." dkd_icon="clock" dkd_action="Veriyi yenile" dkd_onPress={()=>dkd_store.dkd_refreshLive()}/>:<><dkd.Section dkd_title={dkd_oddsReady?'Analiz için hazır':'Güncel fikstür'} dkd_subtitle={dkd_oddsReady?`${dkd_oddsReady} oranlı maçta ${dkd_marketCount} doğrulanmış market seçimi taranıyor.`:'Güncel karşılaşmalar hazır; oran hattı ayrıca doğrulanıyor.'} dkd_action="Tüm maçlar" dkd_onPress={()=>dkd_Router.router.push('/matches')}/>{dkd_focus.slice(0,3).map((dkd_match,dkd_i)=><dkd_liveCard.MatchCard key={dkd_match.dkd_id} dkd_match={dkd_match} dkd_featured={dkd_i===0}/>)}</>}
    <dkd.Section dkd_title="Ritmini seç" dkd_subtitle={dkd_oddsReady?'Her profil veri kalitesi, piyasa olasılığı ve oranı farklı ağırlıklarla sıralar; kesinlik ifade etmez.':'Analiz profilleri doğrulanmış oranı bulunan maçlarda çalışır.'}/><dkd_RN.View style={{flexDirection:'row',flexWrap:'wrap',gap:10}}>{(Object.keys(dkd_risks) as dkd_Risk[]).map(dkd_key=>{const dkd_risk=dkd_risks[dkd_key];return <dkd_RN.Pressable key={dkd_key} accessibilityRole="button" accessibilityLabel={`${dkd_risk.dkd_name} analiz`} onPress={()=>dkd_Router.router.push({pathname:'/builder',params:{dkd_profile:dkd_key}})} style={{width:'48%',flexGrow:1,backgroundColor:dkd_colors.card,borderWidth:1,borderColor:dkd_colors.line,borderRadius:19,padding:16,gap:10}}><dkd.Icon dkd_name={dkd_risk.dkd_icon} dkd_color={dkd_risk.dkd_color}/><dkd.Text dkd_bold dkd_color={dkd_risk.dkd_color}>{dkd_risk.dkd_name}</dkd.Text><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_risk.dkd_subtitle}</dkd.Text></dkd_RN.Pressable>;})}</dkd_RN.View>
    <dkd.Section dkd_title="Veri durumu" dkd_subtitle={`${dkd_leagues} lig/organizasyon · fikstür ve oran akışları bağımsız doğrulanır.`}/>
    <dkd.Card dkd_style={{padding:14,borderRadius:16}}><dkd.Row dkd_between><dkd.Row><dkd.Icon dkd_name="calendar" dkd_size={18} dkd_color={dkd_colors.blue}/><dkd.Text dkd_bold>Bülten akışı</dkd.Text></dkd.Row><dkd.Badge dkd_color={dkd_fixtureReady?dkd_colors.lime:dkd_colors.yellow}>{dkd_fixtureReady?'GÜNCEL':'YENİLENİYOR'}</dkd.Badge></dkd.Row><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_fixtureReady?`${dkd_matches.length} gerçek karşılaşma yüklendi.`:'Güncel karşılaşmalar kontrol ediliyor.'}</dkd.Text></dkd.Card>
    <dkd.Card dkd_style={{padding:14,borderRadius:16}}><dkd.Row dkd_between><dkd.Row><dkd.Icon dkd_name="chart" dkd_size={18} dkd_color={dkd_colors.lime}/><dkd.Text dkd_bold>Oran & market akışı</dkd.Text></dkd.Row><dkd.Badge dkd_color={dkd_oddsReady?dkd_colors.lime:dkd_colors.yellow}>{dkd_oddsReady?'HAZIR':'BEKLENİYOR'}</dkd.Badge></dkd.Row><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_oddsReady?`${dkd_oddsReady} maç · ${dkd_marketCount} seçim analize hazır.`:'Doğrulanmış oranlar geldiğinde analiz otomatik açılır.'}</dkd.Text></dkd.Card>
    <dkd.Button dkd_label="Canlı veriyi yenile" dkd_icon="refresh" dkd_variant="secondary" dkd_onPress={()=>dkd_store.dkd_refreshLive()}/><dkd.Notice dkd_text="Maç sonucu, alt/üst, karşılıklı gol, çifte şans, ilk yarı, tek/çift ve gol aralığı marketleri normalize edildikçe birlikte değerlendirilir. Doğru skor ham olarak gösterilir; tam 9 seçenek bulunan İY/MS marketi normalize edilerek analiz motoruna da katılır. Hiçbir seçim kazanç garantisi değildir."/><dkd.Text dkd_size={10} dkd_color={dkd_colors.muted} dkd_style={{textAlign:'center'}}>DraBornEagle ekosistemi · DKD_draborneagle_v0.5</dkd.Text>
  </dkd.Page>;
}
