import * as dkd_React from 'react';
import * as dkd_RN from 'react-native';
import * as dkd_Router from 'expo-router';
import { dkd, dkd_colors } from '../../src/dkd-ui';
import { dkd_useStore } from '../../src/dkd-store';

export default function dkd_ProfileScreen(){const dkd_store=dkd_useStore();const [dkd_confirm,dkd_setConfirm]=dkd_React.useState(false);const dkd_ok=dkd_store.dkd_sources.filter(dkd_source=>dkd_source.dkd_status==='ok').length;
return <dkd.Page><dkd.Reveal><dkd.Text dkd_size={29} dkd_bold>Canlı sistem<dkd_RN.Text style={{color:dkd_colors.coral}}>.</dkd_RN.Text></dkd.Text><dkd.Text dkd_color={dkd_colors.muted} dkd_size={13}>Kaynak sağlığı, yerel kayıtların ve v0.2 yapılandırması.</dkd.Text></dkd.Reveal>
<dkd.Card><dkd.Row dkd_between><dkd_RN.View><dkd.Text dkd_size={29} dkd_bold dkd_color={dkd_colors.lime}>{dkd_store.dkd_matches.length}</dkd.Text><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>Doğrulanmış maç</dkd.Text></dkd_RN.View><dkd_RN.View><dkd.Text dkd_size={29} dkd_bold dkd_color={dkd_colors.blue}>{dkd_ok}/{dkd_store.dkd_sources.length}</dkd.Text><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>Sağlıklı kaynak</dkd.Text></dkd_RN.View><dkd_RN.View><dkd.Text dkd_size={29} dkd_bold dkd_color={dkd_colors.purple}>{dkd_store.dkd_stored.dkd_coupons.length}</dkd.Text><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>Kayıtlı rapor</dkd.Text></dkd_RN.View></dkd.Row><dkd.Button dkd_label="Canlı veriyi yenile" dkd_icon="refresh" dkd_variant="secondary" dkd_onPress={()=>dkd_store.dkd_refreshLive()}/></dkd.Card>
<dkd.Section dkd_title="Deneyimini kişiselleştir"/><dkd.Card>{[{dkd_key:'dkd_motion' as const,dkd_label:'Arayüz animasyonları',dkd_icon:'spark',dkd_color:dkd_colors.purple},{dkd_key:'dkd_haptics' as const,dkd_label:'Dokunsal geri bildirim',dkd_icon:'bolt',dkd_color:dkd_colors.yellow}].map(dkd_item=><dkd.Row key={dkd_item.dkd_key}><dkd.Icon dkd_name={dkd_item.dkd_icon} dkd_color={dkd_item.dkd_color}/><dkd.Text dkd_bold dkd_size={14} dkd_style={{flex:1}}>{dkd_item.dkd_label}</dkd.Text><dkd_RN.Switch accessibilityLabel={dkd_item.dkd_label} value={dkd_store.dkd_stored.dkd_settings[dkd_item.dkd_key]} trackColor={{false:dkd_colors.line,true:'#486737'}} thumbColor={dkd_store.dkd_stored.dkd_settings[dkd_item.dkd_key]?dkd_colors.lime:dkd_colors.muted} onValueChange={dkd_value=>dkd_store.dkd_setStored(dkd_previous=>({...dkd_previous,dkd_settings:{...dkd_previous.dkd_settings,[dkd_item.dkd_key]:dkd_value}}))}/></dkd.Row>)}</dkd.Card>
<dkd.Section dkd_title="DraBornOdds hakkında"/><dkd.Card><dkd.Row dkd_between><dkd.Text dkd_color={dkd_colors.muted}>Veri modu</dkd.Text><dkd.Badge dkd_color={dkd_colors.lime}>GERÇEK VERİ</dkd.Badge></dkd.Row><dkd.Row dkd_between><dkd.Text dkd_color={dkd_colors.muted}>Sürüm</dkd.Text><dkd.Text dkd_bold>v0.2 · versionCode 1</dkd.Text></dkd.Row><dkd.Row dkd_between><dkd.Text dkd_color={dkd_colors.muted}>Expo Go</dkd.Text><dkd.Text dkd_bold>58.0.0</dkd.Text></dkd.Row><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>Nesine, Misli, Bilyoner ve Tuttur collector durumları Supabase’de yalnızca dbo_ ad alanında tutulur. Koruma mekanizması aşılmaz ve doğrulanamayan veri maç olarak gösterilmez.</dkd.Text><dkd.Button dkd_label="Analiz nasıl çalışır?" dkd_icon="info" dkd_variant="secondary" dkd_onPress={()=>dkd_Router.router.push('/method')}/></dkd.Card>
<dkd.Card dkd_style={{borderColor:'#583932'}}><dkd.Text dkd_bold dkd_color={dkd_colors.coral}>Yerel kayıtları temizle</dkd.Text><dkd.Text dkd_size={13} dkd_color={dkd_colors.muted}>Favorileri, rapor snapshot’larını ve tercihleri bu cihazdan kaldırır; Supabase verisine dokunmaz.</dkd.Text><dkd.Button dkd_label="Yerel kayıtları sıfırla" dkd_icon="refresh" dkd_variant="danger" dkd_onPress={()=>dkd_setConfirm(true)}/></dkd.Card><dkd.Notice dkd_text="Canlı oran ve olasılık bilgileri bilgilendirme amaçlıdır; kazanç garantisi değildir."/><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted} dkd_style={{textAlign:'center'}}>DraBornEagle ekosistemi{'\n'}DKD_draborneagle_v0.2 · Expo SDK 58</dkd.Text><dkd.Confirm dkd_visible={dkd_confirm} dkd_title="Yerel kayıtlar silinsin mi?" dkd_body="Favoriler, kayıtlı rapor snapshot’ları ve tercihler bu cihazdan silinecek." dkd_onCancel={()=>dkd_setConfirm(false)} dkd_onConfirm={()=>{dkd_store.dkd_reset();dkd_setConfirm(false);}}/></dkd.Page>;}
