import * as dkd_React from 'react';
import * as dkd_RN from 'react-native';
import * as dkd_Router from 'expo-router';
import { dkd, dkd_colors } from '../../src/dkd-ui';
import { dkd_useStore } from '../../src/dkd-store';

export default function dkd_ProfileScreen(){
  const dkd_store=dkd_useStore();const [dkd_confirm,dkd_setConfirm]=dkd_React.useState(false);
  return <dkd.Page><dkd.Reveal><dkd.Text dkd_size={29} dkd_bold>Senin alanın<dkd_RN.Text style={{color:dkd_colors.coral}}>.</dkd_RN.Text></dkd.Text></dkd.Reveal>
    <dkd.Card><dkd.Row><dkd_RN.View style={{height:65,width:65,borderRadius:22,alignItems:'center',justifyContent:'center',backgroundColor:dkd_colors.lime}}><dkd.Icon dkd_name="user" dkd_size={32} dkd_color={dkd_colors.bg}/></dkd_RN.View><dkd_RN.View style={{flex:1,gap:5}}><dkd.Text dkd_size={21} dkd_bold>Merhaba, kaşif.</dkd.Text><dkd.Text dkd_color={dkd_colors.muted} dkd_size={13}>DraBornOdds demo deneyimi</dkd.Text><dkd.Badge>DEMO PROFİL</dkd.Badge></dkd_RN.View></dkd.Row><dkd.Row dkd_style={{borderTopWidth:1,borderTopColor:dkd_colors.line,paddingTop:16}}><dkd_RN.View style={{flex:1}}><dkd.Text dkd_size={24} dkd_bold>{dkd_store.dkd_stored.dkd_favorites.length}</dkd.Text><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>Favori maç</dkd.Text></dkd_RN.View><dkd_RN.View style={{flex:1}}><dkd.Text dkd_size={24} dkd_bold>{dkd_store.dkd_stored.dkd_coupons.length}</dkd.Text><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>Kayıtlı rapor</dkd.Text></dkd_RN.View></dkd.Row></dkd.Card>
    <dkd.Section dkd_title="Deneyimini kişiselleştir"/>
    <dkd.Card>{[{dkd_key:'dkd_motion' as const,dkd_label:'Arayüz animasyonları',dkd_body:'Yumuşak geçişler ve hareketli saha',dkd_icon:'spark',dkd_color:dkd_colors.purple},{dkd_key:'dkd_haptics' as const,dkd_label:'Dokunsal geri bildirim',dkd_body:'Seçimlerinde hafif titreşim',dkd_icon:'bolt',dkd_color:dkd_colors.yellow}].map(dkd_item=><dkd.Row key={dkd_item.dkd_key}><dkd.Icon dkd_name={dkd_item.dkd_icon} dkd_color={dkd_item.dkd_color}/><dkd_RN.View style={{flex:1}}><dkd.Text dkd_bold dkd_size={14}>{dkd_item.dkd_label}</dkd.Text><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted}>{dkd_item.dkd_body}</dkd.Text></dkd_RN.View><dkd_RN.Switch accessibilityLabel={dkd_item.dkd_label} value={dkd_store.dkd_stored.dkd_settings[dkd_item.dkd_key]} trackColor={{false:dkd_colors.line,true:'#486737'}} thumbColor={dkd_store.dkd_stored.dkd_settings[dkd_item.dkd_key]?dkd_colors.lime:dkd_colors.muted} onValueChange={dkd_value=>dkd_store.dkd_setStored(dkd_previous=>({...dkd_previous,dkd_settings:{...dkd_previous.dkd_settings,[dkd_item.dkd_key]:dkd_value}}))}/></dkd.Row>)}</dkd.Card>
    <dkd.Section dkd_title="DraBornOdds hakkında"/>
    <dkd.Card><dkd.Row dkd_between><dkd.Text dkd_color={dkd_colors.muted}>Veri modu</dkd.Text><dkd.Badge dkd_color={dkd_colors.blue}>TAMAMEN DEMO</dkd.Badge></dkd.Row><dkd.Row dkd_between><dkd.Text dkd_color={dkd_colors.muted}>Sürüm</dkd.Text><dkd.Text dkd_bold>v0.1</dkd.Text></dkd.Row><dkd.Text dkd_size={12} dkd_color={dkd_colors.muted}>Giriş yapmadan tüm ekranları deneyebilirsin. Favorilerin, raporların ve tercihlerin yalnızca bu cihazda tutulur; bir sunucuya gönderilmez.</dkd.Text><dkd.Button dkd_label="Analiz nasıl çalışır?" dkd_icon="info" dkd_variant="secondary" dkd_onPress={()=>dkd_Router.router.push('/method')}/></dkd.Card>
    <dkd.Card dkd_style={{borderColor:'#583932'}}><dkd.Text dkd_bold dkd_color={dkd_colors.coral}>Sıfırdan bir keşif</dkd.Text><dkd.Text dkd_size={13} dkd_color={dkd_colors.muted}>Favori maçları, kaydedilen raporları ve tercihleri temizleyerek demoyu baştan deneyebilirsin.</dkd.Text><dkd.Button dkd_label="Demo verilerimi sıfırla" dkd_icon="refresh" dkd_variant="danger" dkd_onPress={()=>dkd_setConfirm(true)}/></dkd.Card>
    <dkd.Notice/><dkd.Text dkd_size={11} dkd_color={dkd_colors.muted} dkd_style={{textAlign:'center'}}>DraBornEagle ekosistemi{'\n'}DKD_draborneagle_v0.1 · Expo SDK 58</dkd.Text>
    <dkd.Confirm dkd_visible={dkd_confirm} dkd_title="Demo kayıtları silinsin mi?" dkd_body="Favorilerin, kayıtlı raporların, kupon seçimlerin ve tercihlerin bu cihazdan silinecek. Örnek maçlar kalır." dkd_onCancel={()=>dkd_setConfirm(false)} dkd_onConfirm={()=>{dkd_store.dkd_reset();dkd_setConfirm(false);}}/>
  </dkd.Page>;
}
