import type { dkd_Market, dkd_Match, dkd_Team } from './dkd-types';

export type dkd_TeamStanding={dkd_position:number;dkd_played:number;dkd_wins:number;dkd_draws:number;dkd_losses:number;dkd_goals:string;dkd_points:number};
export type dkd_RecentMatch={dkd_date:string;dkd_opponent:string;dkd_score:string;dkd_venue:'home'|'away'|'unknown';dkd_result:'W'|'D'|'L'|'?'};
export type dkd_TeamContext={dkd_teamName:string;dkd_sourceUrl:string;dkd_logoUrl:string|null;dkd_recent:dkd_RecentMatch[];dkd_standing:dkd_TeamStanding|null;dkd_loaded:boolean};
export type dkd_MatchContext={dkd_home:dkd_TeamContext;dkd_away:dkd_TeamContext;dkd_loaded:boolean};
type dkd_GsaItem={slug?:string;logo?:string;[dkd_key:string]:unknown};
type dkd_GsaSearch={Teams?:dkd_GsaItem[]};
type dkd_GsaResolved={dkd_name:string;dkd_url:string;dkd_logo:string|null};

const dkd_contextCache=new Map<string,dkd_TeamContext>();
const dkd_contextPending=new Map<string,Promise<dkd_TeamContext>>();
const dkd_sponsors=new Set(['tumosan','corendon','arca','caykur','rams','ikas','atakum','bellona']);
const dkd_knownGsa:Record<string,string>={gasogi:'https://globalsportsarchive.com/en/soccer/team/gasogi-united-fc/42590/',gorilla:'https://globalsportsarchive.com/en/soccer/team/gorilla-fc/48840/',mukura:'https://globalsportsarchive.com/en/soccer/team/mukura-victory-sport/14422/',police:'https://globalsportsarchive.com/en/soccer/team/police-fc/14419/'};
function dkd_plain(dkd_value:string){return dkd_value.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ç/g,'c').replace(/ö/g,'o').replace(/ü/g,'u').replace(/[^a-z0-9]+/g,' ').trim();}
function dkd_coreName(dkd_value:string){const dkd_words=dkd_plain(dkd_value).split(/\s+/).filter(Boolean).filter(dkd_word=>!dkd_sponsors.has(dkd_word)&&!['as','a','s','fc','fk','sk','sc','futbol','kulubu','sportif','faaliyetler'].includes(dkd_word));return dkd_words.join(' ').trim();}
function dkd_decode(dkd_value:string){return dkd_value.replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(dkd_all,dkd_code)=>String.fromCodePoint(Number(dkd_code)));}
function dkd_text(dkd_html:string){return dkd_decode(dkd_html.replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim();}
function dkd_absolute(dkd_value:string,dkd_base:string){if(!dkd_value||/^data:/i.test(dkd_value))return null;try{return new URL(dkd_value,dkd_base).toString();}catch{return null;}}
async function dkd_fetch(dkd_url:string,dkd_accept:string){const dkd_controller=new AbortController(),dkd_timer=setTimeout(()=>dkd_controller.abort(),10000);try{const dkd_response=await fetch(dkd_url,{signal:dkd_controller.signal,headers:{Accept:dkd_accept}});if(!dkd_response.ok)throw new Error(`HTTP ${dkd_response.status}`);return dkd_response;}finally{clearTimeout(dkd_timer);}}
async function dkd_searchGsa(dkd_teamName:string):Promise<dkd_GsaResolved|null>{const dkd_known=dkd_knownGsa[dkd_coreName(dkd_teamName)];if(dkd_known)return{dkd_name:dkd_teamName,dkd_url:dkd_known,dkd_logo:null};const dkd_terms=[dkd_teamName,dkd_coreName(dkd_teamName)].filter((dkd_value,dkd_index,dkd_all)=>dkd_value.length>1&&dkd_all.indexOf(dkd_value)===dkd_index);for(const dkd_term of dkd_terms){try{const dkd_url=`https://sport-widgets.com/search/autosearch.php?term=${encodeURIComponent(dkd_term)}`,dkd_body=await(await dkd_fetch(dkd_url,'application/json,text/plain,*/*')).json() as dkd_GsaSearch,dkd_target=dkd_coreName(dkd_teamName),dkd_candidates=(dkd_body.Teams??[]).filter(dkd_item=>String(dkd_item['3']??'').toLowerCase()==='soccer');if(!dkd_candidates.length)continue;const dkd_scored=dkd_candidates.map(dkd_item=>{const dkd_name=String(dkd_item['0']??''),dkd_candidate=dkd_coreName(dkd_name),dkd_score=dkd_candidate===dkd_target?100:dkd_candidate.includes(dkd_target)||dkd_target.includes(dkd_candidate)?80:0;return{dkd_item,dkd_name,dkd_score}}).sort((dkd_left,dkd_right)=>dkd_right.dkd_score-dkd_left.dkd_score),dkd_best=dkd_scored[0];if(!dkd_best)continue;const dkd_slug=String(dkd_best.dkd_item.slug??'').replace(/^\/+|\/+$/g,''),dkd_id=String(dkd_best.dkd_item['2']??'');if(!dkd_slug&&!dkd_id)continue;const dkd_path=dkd_slug||`${dkd_coreName(dkd_best.dkd_name).replace(/ /g,'-')}/${dkd_id}`,dkd_logoRaw=String(dkd_best.dkd_item.logo??'').replace('/50x50/','/200x200/'),dkd_logo=dkd_absolute(dkd_decode(dkd_logoRaw),'https://sport-widgets.com/');return{dkd_name:dkd_best.dkd_name||dkd_teamName,dkd_url:`https://globalsportsarchive.com/en/soccer/team/${dkd_path}/`,dkd_logo};}catch{continue;}}return null;}
function dkd_pageLogo(dkd_html:string,dkd_base:string,dkd_fallback:string|null){const dkd_header=dkd_html.match(/<img\b[^>]*class=["'][^"']*gsa-match-team-header__back[^"']*["'][^>]*>/i)?.[0]??'',dkd_source=dkd_header.match(/src=["']([^"']+)["']/i)?.[1]??'';return dkd_absolute(dkd_decode(dkd_source),dkd_base)??dkd_absolute(dkd_fallback??'',dkd_base);}
function dkd_parseDate(dkd_value:string){const dkd_match=dkd_value.match(/(\d{1,2})\.(\d{1,2})\.(\d{4})/);return dkd_match?Date.UTC(Number(dkd_match[3]),Number(dkd_match[2])-1,Number(dkd_match[1])):0;}
function dkd_recent(dkd_html:string,dkd_teamName:string){const dkd_out:dkd_RecentMatch[]=[],dkd_target=dkd_coreName(dkd_teamName),dkd_pattern=/<a\b[^>]*href=["'][^"']*\/soccer\/match\/[^"']+["'][^>]*class=["'][^"']*gsa-match-rounds-v2__match[^"']*["'][^>]*>([\s\S]*?)<\/a>/gi;for(const dkd_match of dkd_html.matchAll(dkd_pattern)){const dkd_block=dkd_match[1]??'',dkd_date=dkd_text(dkd_block.match(/gsa-match-rounds-v2__match-clock[^>]*>([\s\S]*?)<\/p>/i)?.[1]??''),dkd_teamNames=[...dkd_block.matchAll(/alt=["']logo of ([^"']+)["']/gi)].map(dkd_value=>dkd_decode(dkd_value[1]??'')).filter((dkd_value,dkd_index,dkd_all)=>dkd_all.indexOf(dkd_value)===dkd_index);if(!dkd_date||dkd_teamNames.length<2)continue;const dkd_left=dkd_teamNames[0]??'',dkd_right=dkd_teamNames[1]??'',dkd_isHome=dkd_coreName(dkd_left)===dkd_target,dkd_isAway=dkd_coreName(dkd_right)===dkd_target;if(!dkd_isHome&&!dkd_isAway)continue;const dkd_scoreText=dkd_text(dkd_block.match(/gsa-match-rounds-v2__match-score[^>]*>([\s\S]*?)<\/div>\s*<\/div>/i)?.[1]??''),dkd_score=dkd_scoreText.match(/\b(\d+)\s*:\s*(\d+)\b/)?.[0]??'';if(!dkd_score)continue;const dkd_result=(dkd_block.match(/gsa-text-(?:green|yellow|red)[^>]*>\s*([WDL])\s*</i)?.[1]??'?') as dkd_RecentMatch['dkd_result'];dkd_out.push({dkd_date,dkd_opponent:dkd_isHome?dkd_right:dkd_left,dkd_score,dkd_venue:dkd_isHome?'home':'away',dkd_result});}return dkd_out.sort((dkd_left,dkd_right)=>dkd_parseDate(dkd_right.dkd_date)-dkd_parseDate(dkd_left.dkd_date)).slice(0,8);}
function dkd_stat(dkd_row:string,dkd_key:string){return Number(dkd_text(dkd_row.match(new RegExp(`gsa-comp-table__stat-${dkd_key}[^>]*>([\\s\\S]*?)<\\/div>`,'i'))?.[1]??''))||0;}
function dkd_standing(dkd_html:string,dkd_teamName:string){const dkd_sectionStart=dkd_html.search(/class=["'][^"']*gsa-team-standings[^"']*["']/i);if(dkd_sectionStart<0)return null;const dkd_section=dkd_html.slice(dkd_sectionStart,dkd_sectionStart+180000),dkd_target=dkd_coreName(dkd_teamName),dkd_rows=dkd_section.split(/(?=<div\b[^>]*class=["'][^"']*gsa-comp-table__row\s)/i).slice(1);for(const dkd_row of dkd_rows){const dkd_logoName=dkd_decode(dkd_row.match(/alt=["']logo of ([^"']+)["']/i)?.[1]??'');if(!dkd_logoName||dkd_coreName(dkd_logoName)!==dkd_target)continue;const dkd_position=Number(dkd_text(dkd_row.match(/gsa-comp-table__row-ranking[^>]*>([\s\S]*?)<\/div>/i)?.[1]??''))||0,dkd_played=dkd_stat(dkd_row,'matches_total'),dkd_wins=dkd_stat(dkd_row,'matches_won'),dkd_draws=dkd_stat(dkd_row,'matches_draw'),dkd_losses=dkd_stat(dkd_row,'matches_lost'),dkd_for=dkd_stat(dkd_row,'score_for'),dkd_against=dkd_stat(dkd_row,'score_against'),dkd_points=dkd_stat(dkd_row,'points');if(!dkd_position&&!dkd_played)return null;return{dkd_position,dkd_played,dkd_wins,dkd_draws,dkd_losses,dkd_goals:`${dkd_for}:${dkd_against}`,dkd_points};}return null;}
export async function dkd_fetchTeamContext(dkd_team:dkd_Team):Promise<dkd_TeamContext>{const dkd_key=dkd_plain(dkd_team.dkd_name),dkd_cached=dkd_contextCache.get(dkd_key);if(dkd_cached)return dkd_cached;const dkd_pending=dkd_contextPending.get(dkd_key);if(dkd_pending)return dkd_pending;const dkd_request=(async()=>{let dkd_sourceUrl='https://globalsportsarchive.com/en/';try{const dkd_resolved=await dkd_searchGsa(dkd_team.dkd_name);if(!dkd_resolved)throw new Error('Takım profili bulunamadı');dkd_sourceUrl=dkd_resolved.dkd_url;const dkd_html=await(await dkd_fetch(dkd_resolved.dkd_url,'text/html,application/xhtml+xml')).text(),dkd_value:dkd_TeamContext={dkd_teamName:dkd_team.dkd_name,dkd_sourceUrl:dkd_resolved.dkd_url,dkd_logoUrl:dkd_pageLogo(dkd_html,dkd_resolved.dkd_url,dkd_resolved.dkd_logo),dkd_recent:dkd_recent(dkd_html,dkd_resolved.dkd_name),dkd_standing:dkd_standing(dkd_html,dkd_resolved.dkd_name),dkd_loaded:true};dkd_contextCache.set(dkd_key,dkd_value);return dkd_value;}catch{const dkd_value:dkd_TeamContext={dkd_teamName:dkd_team.dkd_name,dkd_sourceUrl:dkd_sourceUrl,dkd_logoUrl:null,dkd_recent:[],dkd_standing:null,dkd_loaded:false};dkd_contextCache.set(dkd_key,dkd_value);return dkd_value;}finally{dkd_contextPending.delete(dkd_key);}})();dkd_contextPending.set(dkd_key,dkd_request);return dkd_request;}
export async function dkd_fetchMatchContext(dkd_match:dkd_Match):Promise<dkd_MatchContext>{const[dkd_home,dkd_away]=await Promise.all([dkd_fetchTeamContext(dkd_match.dkd_home),dkd_fetchTeamContext(dkd_match.dkd_away)]);return{dkd_home,dkd_away,dkd_loaded:dkd_home.dkd_loaded||dkd_away.dkd_loaded};}
export function dkd_teamFormText(dkd_context:dkd_TeamContext){const dkd_slice=dkd_context.dkd_recent.filter(dkd_item=>dkd_item.dkd_result!=='?').slice(0,5);if(!dkd_slice.length)return'';const dkd_w=dkd_slice.filter(dkd_item=>dkd_item.dkd_result==='W').length,dkd_d=dkd_slice.filter(dkd_item=>dkd_item.dkd_result==='D').length,dkd_l=dkd_slice.filter(dkd_item=>dkd_item.dkd_result==='L').length;let dkd_for=0,dkd_against=0,dkd_scored=0;for(const dkd_item of dkd_slice){const dkd_score=dkd_item.dkd_score.match(/(\d+)\s*:\s*(\d+)/);if(!dkd_score)continue;let dkd_left=Number(dkd_score[1]),dkd_right=Number(dkd_score[2]);if(dkd_item.dkd_venue==='away')[dkd_left,dkd_right]=[dkd_right,dkd_left];dkd_for+=dkd_left;dkd_against+=dkd_right;dkd_scored++;}const dkd_goals=dkd_scored?`; maç başına ${String((dkd_for/dkd_scored).toFixed(1)).replace('.',',')} gol atıp ${String((dkd_against/dkd_scored).toFixed(1)).replace('.',',')} gol yedi`:'';return`son ${dkd_slice.length} maçta ${dkd_w} galibiyet, ${dkd_d} beraberlik, ${dkd_l} mağlubiyet${dkd_goals}`;}
function dkd_standingText(dkd_context:dkd_TeamContext){const dkd_s=dkd_context.dkd_standing;return dkd_s?`${dkd_s.dkd_position}. sırada, ${dkd_s.dkd_points} puanla ${dkd_s.dkd_played} maç oynadı` :'';}
export function dkd_contextReason(dkd_match:dkd_Match,dkd_market:dkd_Market,dkd_context:dkd_MatchContext|null|undefined){const dkd_homeForm=dkd_context?dkd_teamFormText(dkd_context.dkd_home):'',dkd_awayForm=dkd_context?dkd_teamFormText(dkd_context.dkd_away):'',dkd_homeStanding=dkd_context?dkd_standingText(dkd_context.dkd_home):'',dkd_awayStanding=dkd_context?dkd_standingText(dkd_context.dkd_away):'',dkd_parts:string[]=[];if(dkd_homeForm)dkd_parts.push(`${dkd_match.dkd_home.dkd_name} ${dkd_homeForm}`);if(dkd_awayForm)dkd_parts.push(`${dkd_match.dkd_away.dkd_name} ${dkd_awayForm}`);if(dkd_homeStanding||dkd_awayStanding)dkd_parts.push(`Lig tablosunda ${dkd_match.dkd_home.dkd_name}${dkd_homeStanding?` ${dkd_homeStanding}`:' için güncel sıra doğrulanamadı'}; ${dkd_match.dkd_away.dkd_name}${dkd_awayStanding?` ${dkd_awayStanding}`:' için güncel sıra doğrulanamadı'}`);const dkd_label=dkd_market.dkd_label,dkd_direction=dkd_market.dkd_key==='home'?`${dkd_match.dkd_home.dkd_name} tarafını`:dkd_market.dkd_key==='away'?`${dkd_match.dkd_away.dkd_name} tarafını`:dkd_market.dkd_key==='draw'?'beraberliği':`“${dkd_label}” seçimini`;if(dkd_parts.length)return`${dkd_parts.join('. ')}. Bu gerçek geçmiş maç ve sıralama verileri, güncel normalize oranlarla birlikte ${dkd_direction} model açısından değerlendirmeye değer kılan bağlamı oluşturuyor; tek bir istatistik sonucun garantisi değildir.`;return`“${dkd_label}” seçimi güncel karşılıklı oranların normalize olasılığı ve aynı maçtaki alternatif marketlerle karşılaştırılarak öne çıktı. Doğrulanmış geçmiş formu, güncel lig sırası veya xG verisi bulunmadığında bunlar varmış gibi gerekçeye eklenmez.`;}
