import type { dkd_MatchContext, dkd_RecentMatch, dkd_TeamContext } from './dkd-football-context';
import type { dkd_Market, dkd_Match } from './dkd-types';

function dkd_cleanName(dkd_value:string){return dkd_value.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ş/g,'s').replace(/ğ/g,'g').replace(/ç/g,'c').replace(/ö/g,'o').replace(/ü/g,'u').replace(/\b(fc|fk|sk|sc|as|a s)\b/g,' ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function dkd_percent(dkd_value:number){return `%${Math.round(Math.max(0,Math.min(1,dkd_value))*100)}`;}
function dkd_odds(dkd_value:number){return dkd_value.toFixed(2).replace('.',',');}
function dkd_scoreForTeam(dkd_item:dkd_RecentMatch){const dkd_match=dkd_item.dkd_score.match(/(\d+)\s*:\s*(\d+)/);if(!dkd_match)return null;let dkd_for=Number(dkd_match[1]),dkd_against=Number(dkd_match[2]);if(dkd_item.dkd_venue==='away')[dkd_for,dkd_against]=[dkd_against,dkd_for];return{dkd_for,dkd_against};}
function dkd_resultWord(dkd_for:number,dkd_against:number){return dkd_for>dkd_against?'kazandı':dkd_for<dkd_against?'kaybetti':'berabere kaldı';}
function dkd_recentSummary(dkd_name:string,dkd_context:dkd_TeamContext){const dkd_rows=dkd_context.dkd_recent.filter(dkd_item=>!!dkd_scoreForTeam(dkd_item)).slice(0,3);if(!dkd_rows.length)return'';const dkd_games=dkd_rows.map(dkd_item=>{const dkd_score=dkd_scoreForTeam(dkd_item)!;return`${dkd_item.dkd_opponent} karşısında ${dkd_score.dkd_for}-${dkd_score.dkd_against} ${dkd_resultWord(dkd_score.dkd_for,dkd_score.dkd_against)}`;});return`${dkd_name} son maçlarında ${dkd_games.join('; ')}.`;}
function dkd_formSummary(dkd_name:string,dkd_context:dkd_TeamContext){const dkd_rows=dkd_context.dkd_recent.filter(dkd_item=>dkd_item.dkd_result!=='?').slice(0,5);if(!dkd_rows.length)return'';const dkd_w=dkd_rows.filter(dkd_item=>dkd_item.dkd_result==='W').length,dkd_d=dkd_rows.filter(dkd_item=>dkd_item.dkd_result==='D').length,dkd_l=dkd_rows.filter(dkd_item=>dkd_item.dkd_result==='L').length;return`${dkd_name} son ${dkd_rows.length} maçta ${dkd_w} galibiyet, ${dkd_d} beraberlik ve ${dkd_l} mağlubiyet aldı.`;}
function dkd_standingSummary(dkd_match:dkd_Match,dkd_context:dkd_MatchContext){const dkd_home=dkd_context.dkd_home.dkd_standing,dkd_away=dkd_context.dkd_away.dkd_standing;if(!dkd_home&&!dkd_away)return'';if(dkd_home&&dkd_away)return`Lig tablosunda ${dkd_match.dkd_home.dkd_name} ${dkd_home.dkd_position}. sırada ${dkd_home.dkd_points} puanda; ${dkd_match.dkd_away.dkd_name} ${dkd_away.dkd_position}. sırada ${dkd_away.dkd_points} puanda.`;const dkd_only=dkd_home??dkd_away,dkd_name=dkd_home?dkd_match.dkd_home.dkd_name:dkd_match.dkd_away.dkd_name;return dkd_only?`Doğrulanan lig tablosunda ${dkd_name} ${dkd_only.dkd_position}. sırada ve ${dkd_only.dkd_points} puanda.`:'';}
function dkd_h2hSummary(dkd_match:dkd_Match,dkd_context:dkd_MatchContext){const dkd_homeKey=dkd_cleanName(dkd_match.dkd_home.dkd_name),dkd_awayKey=dkd_cleanName(dkd_match.dkd_away.dkd_name);let dkd_rows=dkd_context.dkd_home.dkd_recent.filter(dkd_item=>dkd_cleanName(dkd_item.dkd_opponent)===dkd_awayKey),dkd_from:'home'|'away'='home';if(!dkd_rows.length){dkd_rows=dkd_context.dkd_away.dkd_recent.filter(dkd_item=>dkd_cleanName(dkd_item.dkd_opponent)===dkd_homeKey);dkd_from='away';}const dkd_scores=dkd_rows.slice(0,3).map(dkd_item=>{const dkd_score=dkd_scoreForTeam(dkd_item);if(!dkd_score)return'';const dkd_homeGoals=dkd_from==='home'?dkd_score.dkd_for:dkd_score.dkd_against,dkd_awayGoals=dkd_from==='home'?dkd_score.dkd_against:dkd_score.dkd_for;return`${dkd_homeGoals}-${dkd_awayGoals}`;}).filter(Boolean);if(!dkd_scores.length)return'';return`İki takımın doğrulanabilen son karşılaşmalarında skorlar ${dkd_scores.join(', ')} oldu (ilk sayı ${dkd_match.dkd_home.dkd_name}).`;}
function dkd_marketSummary(dkd_match:dkd_Match,dkd_market:dkd_Market){const dkd_home=dkd_match.dkd_markets.find(dkd_item=>dkd_item.dkd_key==='home'),dkd_draw=dkd_match.dkd_markets.find(dkd_item=>dkd_item.dkd_key==='draw'),dkd_away=dkd_match.dkd_markets.find(dkd_item=>dkd_item.dkd_key==='away');if(dkd_home&&dkd_draw&&dkd_away)return`Güncel 1-X-2 oranları, bahis şirketinin payı çıkarıldıktan sonra yaklaşık olarak ev sahibine ${dkd_percent(dkd_home.dkd_probability)}, beraberliğe ${dkd_percent(dkd_draw.dkd_probability)} ve deplasmana ${dkd_percent(dkd_away.dkd_probability)} ihtimal veriyor. ${dkd_market.dkd_label} seçiminin oranı ${dkd_odds(dkd_market.dkd_odds)}.`;return`${dkd_market.dkd_label} seçiminin güncel oranı ${dkd_odds(dkd_market.dkd_odds)} ve oranlardan hesaplanan yaklaşık ihtimali ${dkd_percent(dkd_market.dkd_probability)}.`;}

export function dkd_friendlyReason(dkd_match:dkd_Match,dkd_market:dkd_Market,dkd_context?:dkd_MatchContext|null){const dkd_parts:string[]=[];if(dkd_context?.dkd_loaded){const dkd_homeForm=dkd_formSummary(dkd_match.dkd_home.dkd_name,dkd_context.dkd_home),dkd_awayForm=dkd_formSummary(dkd_match.dkd_away.dkd_name,dkd_context.dkd_away),dkd_homeRecent=dkd_recentSummary(dkd_match.dkd_home.dkd_name,dkd_context.dkd_home),dkd_awayRecent=dkd_recentSummary(dkd_match.dkd_away.dkd_name,dkd_context.dkd_away),dkd_standing=dkd_standingSummary(dkd_match,dkd_context),dkd_h2h=dkd_h2hSummary(dkd_match,dkd_context);if(dkd_homeForm)dkd_parts.push(dkd_homeForm);if(dkd_awayForm)dkd_parts.push(dkd_awayForm);if(dkd_homeRecent)dkd_parts.push(dkd_homeRecent);if(dkd_awayRecent)dkd_parts.push(dkd_awayRecent);if(dkd_h2h)dkd_parts.push(dkd_h2h);if(dkd_standing)dkd_parts.push(dkd_standing);}const [dkd_homeAbs,dkd_awayAbs]=dkd_match.dkd_absences;if(dkd_homeAbs+dkd_awayAbs>0)dkd_parts.push(`Doğrulanmış kadro bilgisinde ev sahibinde ${dkd_homeAbs}, deplasmanda ${dkd_awayAbs} eksik oyuncu bulunuyor.`);const [dkd_homeRest,dkd_awayRest]=dkd_match.dkd_rest;if(dkd_homeRest>0&&dkd_awayRest>0)dkd_parts.push(`Dinlenme süresi ev sahibi için ${dkd_homeRest}, deplasman için ${dkd_awayRest} gün.`);dkd_parts.push(dkd_marketSummary(dkd_match,dkd_market));if(!dkd_context?.dkd_loaded)dkd_parts.push('Takımların son maçları veya lig sırası doğrulanamadığı için bu karşılaşmada uydurma form bilgisi eklenmedi; seçim ağırlıklı olarak doğrulanmış güncel oranlara göre sıralandı.');dkd_parts.push(`Bu veriler birlikte değerlendirildiğinde “${dkd_market.dkd_label}” seçimi diğer uygun seçeneklerin önüne geçti. Bu bir kesin sonuç tahmini değildir.`);return dkd_parts.join(' ');}
