const dkd_sources={nesine:{name:'Nesine',url:'https://www.nesine.com/iddaa/futbol'},misli:{name:'Misli',url:'https://www.misli.com/iddaa-futbol'},bilyoner:{name:'Bilyoner',url:'https://www.bilyoner.com/iddaa/populer-bahisler'},tuttur:{name:'Tuttur',url:'https://www.tuttur.com/bulten'}};
const dkd_alias={home:['homeTeam','home_team','homeName','home_name','home'],away:['awayTeam','away_team','awayName','away_name','away'],start:['startDate','start_date','startTime','start_time','eventDate','event_date','date'],id:['eventId','event_id','matchId','match_id','fixtureId','fixture_id','id'],league:['leagueName','league_name','tournamentName','tournament_name','league','tournament'],country:['countryName','country_name','country']};
const dkd_text=v=>typeof v==='string'?v:typeof v?.name==='string'?v.name:typeof v?.title==='string'?v.title:'';
const dkd_get=(o,keys)=>{for(const k of keys)if(o&&o[k]!=null)return o[k];};
const dkd_num=v=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)&&n>1.001&&n<1000?n:0;};
function dkd_start(v){if(typeof v==='number')return new Date(v<1e12?v*1000:v).toISOString();if(typeof v==='string'){const d=new Date(v);if(!Number.isNaN(d.getTime()))return d.toISOString();}return'';}
function dkd_odds(o){let h=dkd_num(dkd_get(o,['homeOdds','home_odds','odd1','ms1'])),d=dkd_num(dkd_get(o,['drawOdds','draw_odds','oddX','msX'])),a=dkd_num(dkd_get(o,['awayOdds','away_odds','odd2','ms2']));const box=dkd_get(o,['odds','prices','matchResult','match_result']);if(box&&!Array.isArray(box)&&typeof box==='object'){h=h||dkd_num(dkd_get(box,['1','home','HOME']));d=d||dkd_num(dkd_get(box,['X','x','draw','DRAW']));a=a||dkd_num(dkd_get(box,['2','away','AWAY']));}const markets=Array.isArray(o?.markets)?o.markets:Array.isArray(o?.betOffers)?o.betOffers:[];for(const m of markets){const label=String(m?.name??m?.label??m?.marketName??'').toLocaleLowerCase('tr-TR');if(!/maç sonucu|mac sonucu|match result|1x2/.test(label))continue;const outcomes=Array.isArray(m?.outcomes)?m.outcomes:Array.isArray(m?.selections)?m.selections:Array.isArray(m?.options)?m.options:[];for(const x of outcomes){const label=String(x?.name??x?.label??x?.shortName??x?.code??'').trim().toUpperCase();const price=dkd_num(x?.odds??x?.price??x?.value);if(label==='1'||label==='HOME')h=h||price;if(label==='X'||label==='DRAW')d=d||price;if(label==='2'||label==='AWAY')a=a||price;}}return[h,d,a];}
function dkd_candidate(o,sourceUrl){if(!o||typeof o!=='object'||Array.isArray(o))return null;const home=dkd_text(dkd_get(o,dkd_alias.home)).trim(),away=dkd_text(dkd_get(o,dkd_alias.away)).trim();if(home.length<2||away.length<2||home===away)return null;const start=dkd_start(dkd_get(o,dkd_alias.start));if(!start)return null;const [homeOdds,drawOdds,awayOdds]=dkd_odds(o);if(!homeOdds||!drawOdds||!awayOdds)return null;const id=String(dkd_get(o,dkd_alias.id)??`${start}_${home}_${away}`).slice(0,280);return{source_match_id:id,home,away,league:dkd_text(dkd_get(o,dkd_alias.league)).slice(0,120)||'Futbol',country:dkd_text(dkd_get(o,dkd_alias.country)).slice(0,80)||undefined,start_at:start,source_url:sourceUrl,home_odds:homeOdds,draw_odds:drawOdds,away_odds:awayOdds};}
function dkd_walk(value,sourceUrl,out,seen,depth=0){if(depth>14||value==null)return;if(Array.isArray(value)){for(const x of value.slice(0,5000))dkd_walk(x,sourceUrl,out,seen,depth+1);return;}if(typeof value!=='object')return;const c=dkd_candidate(value,sourceUrl);if(c){const k=`${c.source_match_id}|${c.home}|${c.away}`;if(!seen.has(k)){seen.add(k);out.push(c);}}for(const v of Object.values(value))dkd_walk(v,sourceUrl,out,seen,depth+1);}
function dkd_jsonScripts(html){const values=[];for(const match of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)){const raw=match[1].trim();if(!raw||raw.length>8_000_000)continue;const tries=[raw];const firstObj=raw.indexOf('{'),lastObj=raw.lastIndexOf('}');if(firstObj>=0&&lastObj>firstObj)tries.push(raw.slice(firstObj,lastObj+1));const firstArr=raw.indexOf('['),lastArr=raw.lastIndexOf(']');if(firstArr>=0&&lastArr>firstArr)tries.push(raw.slice(firstArr,lastArr+1));for(const text of tries){try{values.push(JSON.parse(text));break;}catch{}}}return values;}
async function dkd_collect(id){const source=dkd_sources[id];const started=Date.now();try{const response=await fetch(source.url,{redirect:'follow',headers:{'user-agent':'DraBornOddsCollector/0.2 (+https://github.com/DrabornEagle/DraBornOdds)','accept':'text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.5','accept-language':'tr-TR,tr;q=0.9'}});const html=await response.text();const lower=html.toLowerCase();const blocked=response.status===401||response.status===403||response.status===429||/access denied|captcha|cloudflare|bot detection|robot doğrulama|erişim engellendi/.test(lower);const candidates=[],seen=new Set();if(!blocked)for(const value of dkd_jsonScripts(html))dkd_walk(value,response.url,candidates,seen);return{source_id:id,status:blocked?'blocked':candidates.length?'ok':response.ok?'degraded':'error',http_status:response.status,fetched_bytes:new TextEncoder().encode(html).length,error:blocked?'Kaynak otomatik erişimi koruma katmanına yönlendirdi; koruma aşılmadı.':candidates.length?'':response.ok?'Sayfa erişilebilir ancak doğrulanabilir 1X2 yapılandırılmış veri ayrıştırılamadı.':`HTTP ${response.status}`,candidates,duration_ms:Date.now()-started};}catch(e){return{source_id:id,status:'error',error:e instanceof Error?e.message:String(e),candidates:[],duration_ms:Date.now()-started};}}
const ids=process.argv.slice(2).filter(id=>Object.hasOwn(dkd_sources,id));const selected=ids.length?ids:Object.keys(dkd_sources);const results=[];for(const id of selected)results.push(await dkd_collect(id));process.stdout.write(JSON.stringify({collector_version:'dbo_v0.2.2',generated_at:new Date().toISOString(),results},null,2));
